package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.Car;

public interface CarMapper<T> extends IBaseMapper<T> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCAR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCAR
     *
     * @mbggenerated
     */
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCAR
     *
     * @mbggenerated
     */
    int insertSelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCAR
     *
     * @mbggenerated
     */
    Car selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCAR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TCAR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Car record);

	int selectNo();
}