package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.Message;
import com.yttx.yttxps.model.MessageExample;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MessageMapper extends IBaseMapper<Message>{
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	int countByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	int deleteByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	List<Message> selectByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	Message selectByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Message record,
			@Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	int updateByExample(@Param("record") Message record,
			@Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TMESSAGE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	int updateByPrimaryKey(Message record);

	/**
     * 获取sequence主键
     * @return
     */
    BigDecimal selectFsNo();

	List<Message> selectUnreadMsg(Map<String, Object> map);

    
}