package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.Pic;
import java.math.BigDecimal;

public interface PicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPIC
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal fiIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPIC
     *
     * @mbggenerated
     */
    int insert(Pic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPIC
     *
     * @mbggenerated
     */
    int insertSelective(Pic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPIC
     *
     * @mbggenerated
     */
    Pic selectByPrimaryKey(BigDecimal fiIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPIC
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPIC
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pic record);
}