package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.RegionMap;

public interface RegionMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TREGIONMAP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fsNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TREGIONMAP
     *
     * @mbggenerated
     */
    int insert(RegionMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TREGIONMAP
     *
     * @mbggenerated
     */
    int insertSelective(RegionMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TREGIONMAP
     *
     * @mbggenerated
     */
    RegionMap selectByPrimaryKey(String fsNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TREGIONMAP
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RegionMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TREGIONMAP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RegionMap record);
}