package com.yttx.yttxps.mapper;

import java.util.List;
import java.util.Map;

import com.yttx.yttxps.model.SysOper;
import com.yttx.yttxps.model.SysOperExample;
import org.apache.ibatis.annotations.Param;

public interface SysOperMapper<T> extends IBaseMapper<T>{
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	int countByExample(SysOperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	int deleteByExample(SysOperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	int deleteByPrimaryKey(String sysOperId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	int insert(SysOper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	int insertSelective(SysOper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	List<SysOper> selectByExample(SysOperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	SysOper selectByPrimaryKey(String sysOperId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SysOper record,
			@Param("example") SysOperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	int updateByExample(@Param("record") SysOper record,
			@Param("example") SysOperExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	int updateByPrimaryKeySelective(SysOper record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSYSOPER
	 * @mbggenerated  Tue May 10 15:31:06 CST 2016
	 */
	int updateByPrimaryKey(SysOper record);

	public SysOper findById(String  sysOperId);
	
	public int  update(SysOper sysOper);

	public void updateOperStatByDepNo(SysOper oper);
    
    /**
     * 更新用户信息
     */
    public boolean updateOperByOperId(Map<String, Object> map);

    /**
     * 删除�?��用户
     */
	public void deleteOperByOperId(String sysOperId);

	/**
	 * 通过部门编号找到部门下所有人�?
	 */
	public List<SysOper> selectOpersByDepNo(Long depNo);
}
