package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.Tgen;
import java.math.BigDecimal;
import com.yttx.yttxps.model.TgenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TgenMapper<T> extends IBaseMapper<T>  {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int countByExample(TgenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int deleteByExample(TgenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal fiIndex);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int insert(Tgen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int insertSelective(Tgen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	List<Tgen> selectByExample(TgenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	Tgen selectByPrimaryKey(BigDecimal fiIndex);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Tgen record,
			@Param("example") TgenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int updateByExample(@Param("record") Tgen record,
			@Param("example") TgenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int updateByPrimaryKeySelective(Tgen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TGEN
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int updateByPrimaryKey(Tgen record);
	
	/**
	 * 获取路线序列
	 * @return
	 */
    int selectFiIndex();
}