package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.Tguide;

public interface TguideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TGUIDE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TGUIDE
     *
     * @mbggenerated
     */
    int insert(Tguide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TGUIDE
     *
     * @mbggenerated
     */
    int insertSelective(Tguide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TGUIDE
     *
     * @mbggenerated
     */
    Tguide selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TGUIDE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tguide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TGUIDE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tguide record);
}