package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.TOrderlist;
import com.yttx.yttxps.model.TOrderlistExample;
import com.yttx.yttxps.model.TOrderlistWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOrderlistMapper<T> extends IBaseMapper<T> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int countByExample(TOrderlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int deleteByExample(TOrderlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int deleteByPrimaryKey(String fsNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int insert(TOrderlistWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int insertSelective(TOrderlistWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	List<TOrderlistWithBLOBs> selectByExampleWithBLOBs(TOrderlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	List<TOrderlist> selectByExample(TOrderlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	TOrderlistWithBLOBs selectByPrimaryKey(String fsNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TOrderlistWithBLOBs record,
			@Param("example") TOrderlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") TOrderlistWithBLOBs record,
			@Param("example") TOrderlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int updateByExample(@Param("record") TOrderlist record,
			@Param("example") TOrderlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int updateByPrimaryKeySelective(TOrderlistWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(TOrderlistWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERLIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	int updateByPrimaryKey(TOrderlist record);
}