package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.TOrderCusList;
import com.yttx.yttxps.model.TOrderCusListExample;
import com.yttx.yttxps.model.TOrderCusListKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOrderCusListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    int countByExample(TOrderCusListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    int deleteByExample(TOrderCusListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    int deleteByPrimaryKey(TOrderCusListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    int insert(TOrderCusList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    int insertSelective(TOrderCusList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    List<TOrderCusList> selectByExample(TOrderCusListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    TOrderCusList selectByPrimaryKey(TOrderCusListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TOrderCusList record, @Param("example") TOrderCusListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    int updateByExample(@Param("record") TOrderCusList record, @Param("example") TOrderCusListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    int updateByPrimaryKeySelective(TOrderCusList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TORDERCUSLIST
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    int updateByPrimaryKey(TOrderCusList record);
}