package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.TOrderCustom;
import com.yttx.yttxps.model.TOrderCustomExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yttx.yttxps.model.TOrderCustomWithBLOBs;

public interface TOrderCustomMapper<T> extends IBaseMapper<T> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int countByExample(TOrderCustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int deleteByExample(TOrderCustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal fiId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int insert(TOrderCustomWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int insertSelective(TOrderCustomWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	List<TOrderCustomWithBLOBs> selectByExampleWithBLOBs(
			TOrderCustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	List<TOrderCustom> selectByExample(TOrderCustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	TOrderCustomWithBLOBs selectByPrimaryKey(BigDecimal fiId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TOrderCustomWithBLOBs record,
			@Param("example") TOrderCustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") TOrderCustomWithBLOBs record,
			@Param("example") TOrderCustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int updateByExample(@Param("record") TOrderCustom record,
			@Param("example") TOrderCustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int updateByPrimaryKeySelective(TOrderCustomWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(TOrderCustomWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TORDERCUSTOM
	 * @mbggenerated  Sun Feb 21 14:08:05 CST 2016
	 */
	int updateByPrimaryKey(TOrderCustom record);
}