package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.TRestaurant;

public interface TRestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRESTAURANT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRESTAURANT
     *
     * @mbggenerated
     */
    int insert(TRestaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRESTAURANT
     *
     * @mbggenerated
     */
    int insertSelective(TRestaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRESTAURANT
     *
     * @mbggenerated
     */
    TRestaurant selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRESTAURANT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TRestaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRESTAURANT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TRestaurant record);
}