package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.Trlist;
import com.yttx.yttxps.model.TrlistExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrlistMapper<T> extends IBaseMapper<T>  {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	int countByExample(TrlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	int deleteByExample(TrlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal fiTrseq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	int insert(Trlist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	int insertSelective(Trlist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	List<Trlist> selectByExample(TrlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	Trlist selectByPrimaryKey(BigDecimal fiTrseq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Trlist record,
			@Param("example") TrlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	int updateByExample(@Param("record") Trlist record,
			@Param("example") TrlistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	int updateByPrimaryKeySelective(Trlist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	int updateByPrimaryKey(Trlist record);

	/**
     * 获取流水序列�?
     * @return
     */
    int selectTrSeq();
}