package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.Troom;
import java.math.BigDecimal;

public interface TroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TROOM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal index);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TROOM
     *
     * @mbggenerated
     */
    int insert(Troom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TROOM
     *
     * @mbggenerated
     */
    int insertSelective(Troom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TROOM
     *
     * @mbggenerated
     */
    Troom selectByPrimaryKey(BigDecimal index);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TROOM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Troom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TROOM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Troom record);
}