package com.yttx.yttxps.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yttx.yttxps.model.RouteCCType;
import com.yttx.yttxps.model.TRouteArrange;
import com.yttx.yttxps.model.TRouteArrangeExample;
import com.yttx.yttxps.model.TRouteArrangeWithBLOBs;
import com.yttx.yttxps.model.VResSnapshot;

public interface TRouteArrangeMapper<T> extends IBaseMapper<T> {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int countByExample(TRouteArrangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int deleteByExample(TRouteArrangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int deleteByPrimaryKey(String fsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int insert(TRouteArrangeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int insertSelective(TRouteArrangeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	List<TRouteArrangeWithBLOBs> selectByExampleWithBLOBs(
			TRouteArrangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	List<TRouteArrange> selectByExample(TRouteArrangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	TRouteArrangeWithBLOBs selectByPrimaryKey(String fsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int updateByExampleSelective(
			@Param("record") TRouteArrangeWithBLOBs record,
			@Param("example") TRouteArrangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int updateByExampleWithBLOBs(
			@Param("record") TRouteArrangeWithBLOBs record,
			@Param("example") TRouteArrangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int updateByExample(@Param("record") TRouteArrange record,
			@Param("example") TRouteArrangeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int updateByPrimaryKeySelective(TRouteArrangeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(TRouteArrangeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TROUTEARRANGE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	int updateByPrimaryKey(TRouteArrange record);
	
	List<RouteCCType> selectRouteCCType(Map<String, Object> map);
	
	List<VResSnapshot> selectRessnapshot(Map<String, Object> map);
	
	/**
	 * @author marongcai
	 * 查询线路报价
	 */
	List<Map<String,Object>> selectCost(Map<String,String> map);

	int selectFsId();
}