package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.TScenicGen;
import java.math.BigDecimal;
import com.yttx.yttxps.model.TScenicGenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TScenicGenMapper<T> extends IBaseMapper<T> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	int countByExample(TScenicGenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	int deleteByExample(TScenicGenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	int deleteByPrimaryKey(BigDecimal fiIndex);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	int insert(TScenicGen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	int insertSelective(TScenicGen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	List<TScenicGen> selectByExample(TScenicGenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	TScenicGen selectByPrimaryKey(BigDecimal fiIndex);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TScenicGen record,
			@Param("example") TScenicGenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	int updateByExample(@Param("record") TScenicGen record,
			@Param("example") TScenicGenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	int updateByPrimaryKeySelective(TScenicGen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TSCENICGEN
	 * @mbggenerated  Fri Jan 22 21:17:13 CST 2016
	 */
	int updateByPrimaryKey(TScenicGen record);
	
	BigDecimal selectFiIndex();
}