package com.yttx.yttxps.mapper;

import java.util.List;

import com.yttx.yttxps.model.Tshop;
import com.yttx.yttxps.model.TshopExample;

public interface TshopMapper<T> extends IBaseMapper<T> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSHOP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSHOP
     *
     * @mbggenerated
     */
    int insert(Tshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSHOP
     *
     * @mbggenerated
     */
    int insertSelective(Tshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSHOP
     *
     * @mbggenerated
     */
    Tshop selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSHOP
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSHOP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tshop record);
    
    List<Tshop> selectByExample(TshopExample example);
}