package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.Tticket;

public interface TticketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTICKET
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTICKET
     *
     * @mbggenerated
     */
    int insert(Tticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTICKET
     *
     * @mbggenerated
     */
    int insertSelective(Tticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTICKET
     *
     * @mbggenerated
     */
    Tticket selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTICKET
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTICKET
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tticket record);
}