package com.yttx.yttxps.mapper;

import com.yttx.yttxps.model.Ttransport;
import com.yttx.yttxps.model.TtransportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtransportMapper<T> extends IBaseMapper<T> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int countByExample(TtransportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int deleteByExample(TtransportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int deleteByPrimaryKey(String fsNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int insert(Ttransport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int insertSelective(Ttransport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	List<Ttransport> selectByExample(TtransportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	Ttransport selectByPrimaryKey(String fsNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Ttransport record,
			@Param("example") TtransportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int updateByExample(@Param("record") Ttransport record,
			@Param("example") TtransportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int updateByPrimaryKeySelective(Ttransport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRANSPORT
	 * @mbggenerated  Sun Jan 10 16:31:14 CST 2016
	 */
	int updateByPrimaryKey(Ttransport record);
}