DELETE FROM TResCC;

--门票
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000001');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000002');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000003');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000004');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000005');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000006');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000007');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000008');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000009');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000010');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000011');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000012');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000013');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000014');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000015');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('mp','000016');

--娱乐
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000001');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000002');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000003');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000004');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000005');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000006');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000007');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000008');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000009');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000010');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000011');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000012');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000013');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000014');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000015');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000016');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('yl','000017');

--餐厅
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('ct','000018');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('ct','000019');
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('ct','000020');

--车型线路
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('cx','000023');

--导游
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('dy','000000');

--宾馆
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('bg','000024');

--购物点
INSERT INTO TResCC(FS_RESTYPE,FS_CCNO) VALUES('gw','000021');

COMMIT;
EXIT;