package com.yttx.yttxps.model;

public class CustomOperKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TCUSTOMOPER.FS_ID
	 * @mbggenerated  Tue Apr 19 11:18:20 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TCUSTOMOPER.FS_SUBID
	 * @mbggenerated  Tue Apr 19 11:18:20 CST 2016
	 */
	private String subid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TCUSTOMOPER.FS_ID
	 * @return  the value of TCUSTOMOPER.FS_ID
	 * @mbggenerated  Tue Apr 19 11:18:20 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TCUSTOMOPER.FS_ID
	 * @param id  the value for TCUSTOMOPER.FS_ID
	 * @mbggenerated  Tue Apr 19 11:18:20 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TCUSTOMOPER.FS_SUBID
	 * @return  the value of TCUSTOMOPER.FS_SUBID
	 * @mbggenerated  Tue Apr 19 11:18:20 CST 2016
	 */
	public String getSubid() {
		return subid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TCUSTOMOPER.FS_SUBID
	 * @param subid  the value for TCUSTOMOPER.FS_SUBID
	 * @mbggenerated  Tue Apr 19 11:18:20 CST 2016
	 */
	public void setSubid(String subid) {
		this.subid = subid;
	}
}