package com.yttx.yttxps.model;

public class DictKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDICT.FS_DICTNO
     *
     * @mbggenerated Sun Feb 14 15:29:35 CST 2016
     */
    private String fsDictno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDICT.FS_PARENTNO
     *
     * @mbggenerated Sun Feb 14 15:29:35 CST 2016
     */
    private String fsParentno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDICT.FS_DICTNO
     *
     * @return the value of TDICT.FS_DICTNO
     *
     * @mbggenerated Sun Feb 14 15:29:35 CST 2016
     */
    public String getFsDictno() {
        return fsDictno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDICT.FS_DICTNO
     *
     * @param fsDictno the value for TDICT.FS_DICTNO
     *
     * @mbggenerated Sun Feb 14 15:29:35 CST 2016
     */
    public void setFsDictno(String fsDictno) {
        this.fsDictno = fsDictno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDICT.FS_PARENTNO
     *
     * @return the value of TDICT.FS_PARENTNO
     *
     * @mbggenerated Sun Feb 14 15:29:35 CST 2016
     */
    public String getFsParentno() {
        return fsParentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDICT.FS_PARENTNO
     *
     * @param fsParentno the value for TDICT.FS_PARENTNO
     *
     * @mbggenerated Sun Feb 14 15:29:35 CST 2016
     */
    public void setFsParentno(String fsParentno) {
        this.fsParentno = fsParentno;
    }
}