package com.yttx.yttxps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public MessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("FI_ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("FI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("FI_ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("FI_ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("FI_ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FI_ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("FI_ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FI_ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("FI_ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("FI_ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FI_ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FI_ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSendTypeIsNull() {
            addCriterion("FS_SENDTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSendTypeIsNotNull() {
            addCriterion("FS_SENDTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSendTypeEqualTo(String value) {
            addCriterion("FS_SENDTYPE =", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotEqualTo(String value) {
            addCriterion("FS_SENDTYPE <>", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeGreaterThan(String value) {
            addCriterion("FS_SENDTYPE >", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FS_SENDTYPE >=", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLessThan(String value) {
            addCriterion("FS_SENDTYPE <", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLessThanOrEqualTo(String value) {
            addCriterion("FS_SENDTYPE <=", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLike(String value) {
            addCriterion("FS_SENDTYPE like", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotLike(String value) {
            addCriterion("FS_SENDTYPE not like", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeIn(List<String> values) {
            addCriterion("FS_SENDTYPE in", values, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotIn(List<String> values) {
            addCriterion("FS_SENDTYPE not in", values, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeBetween(String value1, String value2) {
            addCriterion("FS_SENDTYPE between", value1, value2, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotBetween(String value1, String value2) {
            addCriterion("FS_SENDTYPE not between", value1, value2, "sendType");
            return (Criteria) this;
        }

        public Criteria andMsgTextIsNull() {
            addCriterion("FS_MSGTEXT is null");
            return (Criteria) this;
        }

        public Criteria andMsgTextIsNotNull() {
            addCriterion("FS_MSGTEXT is not null");
            return (Criteria) this;
        }

        public Criteria andMsgTextEqualTo(String value) {
            addCriterion("FS_MSGTEXT =", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotEqualTo(String value) {
            addCriterion("FS_MSGTEXT <>", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextGreaterThan(String value) {
            addCriterion("FS_MSGTEXT >", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextGreaterThanOrEqualTo(String value) {
            addCriterion("FS_MSGTEXT >=", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextLessThan(String value) {
            addCriterion("FS_MSGTEXT <", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextLessThanOrEqualTo(String value) {
            addCriterion("FS_MSGTEXT <=", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextLike(String value) {
            addCriterion("FS_MSGTEXT like", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotLike(String value) {
            addCriterion("FS_MSGTEXT not like", value, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextIn(List<String> values) {
            addCriterion("FS_MSGTEXT in", values, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotIn(List<String> values) {
            addCriterion("FS_MSGTEXT not in", values, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextBetween(String value1, String value2) {
            addCriterion("FS_MSGTEXT between", value1, value2, "msgText");
            return (Criteria) this;
        }

        public Criteria andMsgTextNotBetween(String value1, String value2) {
            addCriterion("FS_MSGTEXT not between", value1, value2, "msgText");
            return (Criteria) this;
        }

        public Criteria andSendIdIsNull() {
            addCriterion("FS_SENDID is null");
            return (Criteria) this;
        }

        public Criteria andSendIdIsNotNull() {
            addCriterion("FS_SENDID is not null");
            return (Criteria) this;
        }

        public Criteria andSendIdEqualTo(String value) {
            addCriterion("FS_SENDID =", value, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdNotEqualTo(String value) {
            addCriterion("FS_SENDID <>", value, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdGreaterThan(String value) {
            addCriterion("FS_SENDID >", value, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdGreaterThanOrEqualTo(String value) {
            addCriterion("FS_SENDID >=", value, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdLessThan(String value) {
            addCriterion("FS_SENDID <", value, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdLessThanOrEqualTo(String value) {
            addCriterion("FS_SENDID <=", value, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdLike(String value) {
            addCriterion("FS_SENDID like", value, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdNotLike(String value) {
            addCriterion("FS_SENDID not like", value, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdIn(List<String> values) {
            addCriterion("FS_SENDID in", values, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdNotIn(List<String> values) {
            addCriterion("FS_SENDID not in", values, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdBetween(String value1, String value2) {
            addCriterion("FS_SENDID between", value1, value2, "sendId");
            return (Criteria) this;
        }

        public Criteria andSendIdNotBetween(String value1, String value2) {
            addCriterion("FS_SENDID not between", value1, value2, "sendId");
            return (Criteria) this;
        }

        public Criteria andRecvIdIsNull() {
            addCriterion("FS_RECVID is null");
            return (Criteria) this;
        }

        public Criteria andRecvIdIsNotNull() {
            addCriterion("FS_RECVID is not null");
            return (Criteria) this;
        }

        public Criteria andRecvIdEqualTo(String value) {
            addCriterion("FS_RECVID =", value, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdNotEqualTo(String value) {
            addCriterion("FS_RECVID <>", value, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdGreaterThan(String value) {
            addCriterion("FS_RECVID >", value, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdGreaterThanOrEqualTo(String value) {
            addCriterion("FS_RECVID >=", value, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdLessThan(String value) {
            addCriterion("FS_RECVID <", value, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdLessThanOrEqualTo(String value) {
            addCriterion("FS_RECVID <=", value, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdLike(String value) {
            addCriterion("FS_RECVID like", value, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdNotLike(String value) {
            addCriterion("FS_RECVID not like", value, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdIn(List<String> values) {
            addCriterion("FS_RECVID in", values, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdNotIn(List<String> values) {
            addCriterion("FS_RECVID not in", values, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdBetween(String value1, String value2) {
            addCriterion("FS_RECVID between", value1, value2, "recvId");
            return (Criteria) this;
        }

        public Criteria andRecvIdNotBetween(String value1, String value2) {
            addCriterion("FS_RECVID not between", value1, value2, "recvId");
            return (Criteria) this;
        }

        public Criteria andSubIdIsNull() {
            addCriterion("FS_SUBID is null");
            return (Criteria) this;
        }

        public Criteria andSubIdIsNotNull() {
            addCriterion("FS_SUBID is not null");
            return (Criteria) this;
        }

        public Criteria andSubIdEqualTo(String value) {
            addCriterion("FS_SUBID =", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotEqualTo(String value) {
            addCriterion("FS_SUBID <>", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdGreaterThan(String value) {
            addCriterion("FS_SUBID >", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdGreaterThanOrEqualTo(String value) {
            addCriterion("FS_SUBID >=", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdLessThan(String value) {
            addCriterion("FS_SUBID <", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdLessThanOrEqualTo(String value) {
            addCriterion("FS_SUBID <=", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdLike(String value) {
            addCriterion("FS_SUBID like", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotLike(String value) {
            addCriterion("FS_SUBID not like", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdIn(List<String> values) {
            addCriterion("FS_SUBID in", values, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotIn(List<String> values) {
            addCriterion("FS_SUBID not in", values, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdBetween(String value1, String value2) {
            addCriterion("FS_SUBID between", value1, value2, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotBetween(String value1, String value2) {
            addCriterion("FS_SUBID not between", value1, value2, "subId");
            return (Criteria) this;
        }

        public Criteria andMsgDateIsNull() {
            addCriterion("FT_MSGDATE is null");
            return (Criteria) this;
        }

        public Criteria andMsgDateIsNotNull() {
            addCriterion("FT_MSGDATE is not null");
            return (Criteria) this;
        }

        public Criteria andMsgDateEqualTo(Date value) {
            addCriterionForJDBCDate("FT_MSGDATE =", value, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("FT_MSGDATE <>", value, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgDateGreaterThan(Date value) {
            addCriterionForJDBCDate("FT_MSGDATE >", value, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FT_MSGDATE >=", value, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgDateLessThan(Date value) {
            addCriterionForJDBCDate("FT_MSGDATE <", value, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FT_MSGDATE <=", value, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgDateIn(List<Date> values) {
            addCriterionForJDBCDate("FT_MSGDATE in", values, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("FT_MSGDATE not in", values, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FT_MSGDATE between", value1, value2, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FT_MSGDATE not between", value1, value2, "msgDate");
            return (Criteria) this;
        }

        public Criteria andMsgStatIsNull() {
            addCriterion("FI_MSGSTAT is null");
            return (Criteria) this;
        }

        public Criteria andMsgStatIsNotNull() {
            addCriterion("FI_MSGSTAT is not null");
            return (Criteria) this;
        }

        public Criteria andMsgStatEqualTo(BigDecimal value) {
            addCriterion("FI_MSGSTAT =", value, "msgStat");
            return (Criteria) this;
        }

        public Criteria andMsgStatNotEqualTo(BigDecimal value) {
            addCriterion("FI_MSGSTAT <>", value, "msgStat");
            return (Criteria) this;
        }

        public Criteria andMsgStatGreaterThan(BigDecimal value) {
            addCriterion("FI_MSGSTAT >", value, "msgStat");
            return (Criteria) this;
        }

        public Criteria andMsgStatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FI_MSGSTAT >=", value, "msgStat");
            return (Criteria) this;
        }

        public Criteria andMsgStatLessThan(BigDecimal value) {
            addCriterion("FI_MSGSTAT <", value, "msgStat");
            return (Criteria) this;
        }

        public Criteria andMsgStatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FI_MSGSTAT <=", value, "msgStat");
            return (Criteria) this;
        }

        public Criteria andMsgStatIn(List<BigDecimal> values) {
            addCriterion("FI_MSGSTAT in", values, "msgStat");
            return (Criteria) this;
        }

        public Criteria andMsgStatNotIn(List<BigDecimal> values) {
            addCriterion("FI_MSGSTAT not in", values, "msgStat");
            return (Criteria) this;
        }

        public Criteria andMsgStatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FI_MSGSTAT between", value1, value2, "msgStat");
            return (Criteria) this;
        }

        public Criteria andMsgStatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FI_MSGSTAT not between", value1, value2, "msgStat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TMESSAGE
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 18 16:35:51 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TMESSAGE
     *
     * @mbggenerated Mon Apr 18 16:35:51 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}