package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class MessageAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMESSAGEAUTH.FS_ID
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMESSAGEAUTH.FS_MSGTEMP
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    private String msgTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMESSAGEAUTH.FS_RECEIVECONF
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    private String receiveConf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMESSAGEAUTH.FS_DESC
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMESSAGEAUTH.FI_STAT
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    private BigDecimal stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMESSAGEAUTH.FS_ID
     *
     * @return the value of TMESSAGEAUTH.FS_ID
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMESSAGEAUTH.FS_ID
     *
     * @param id the value for TMESSAGEAUTH.FS_ID
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMESSAGEAUTH.FS_MSGTEMP
     *
     * @return the value of TMESSAGEAUTH.FS_MSGTEMP
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public String getMsgTemp() {
        return msgTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMESSAGEAUTH.FS_MSGTEMP
     *
     * @param msgTemp the value for TMESSAGEAUTH.FS_MSGTEMP
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public void setMsgTemp(String msgTemp) {
        this.msgTemp = msgTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMESSAGEAUTH.FS_RECEIVECONF
     *
     * @return the value of TMESSAGEAUTH.FS_RECEIVECONF
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public String getReceiveConf() {
        return receiveConf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMESSAGEAUTH.FS_RECEIVECONF
     *
     * @param receiveConf the value for TMESSAGEAUTH.FS_RECEIVECONF
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public void setReceiveConf(String receiveConf) {
        this.receiveConf = receiveConf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMESSAGEAUTH.FS_DESC
     *
     * @return the value of TMESSAGEAUTH.FS_DESC
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMESSAGEAUTH.FS_DESC
     *
     * @param desc the value for TMESSAGEAUTH.FS_DESC
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMESSAGEAUTH.FI_STAT
     *
     * @return the value of TMESSAGEAUTH.FI_STAT
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public BigDecimal getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMESSAGEAUTH.FI_STAT
     *
     * @param stat the value for TMESSAGEAUTH.FI_STAT
     *
     * @mbggenerated Mon Apr 18 16:35:52 CST 2016
     */
    public void setStat(BigDecimal stat) {
        this.stat = stat;
    }
}