package com.yttx.yttxps.model;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class Message {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FI_ID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FS_SENDTYPE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private String sendType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FS_MSGHEAD
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private String msgHead;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FS_MSGTEXT
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private String msgText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FS_SENDID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private String sendid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FS_RECVID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private String recvid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FS_SUBID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private String subid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FT_MSGDATE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private Date msgDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FI_MSGSTAT
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private String MsgStat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FS_AUTHID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private String authid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TMESSAGE.FS_ID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	private String fsId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FI_ID
	 * @return  the value of TMESSAGE.FI_ID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FI_ID
	 * @param id  the value for TMESSAGE.FI_ID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FS_SENDTYPE
	 * @return  the value of TMESSAGE.FS_SENDTYPE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public String getSendType() {
		return sendType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FS_SENDTYPE
	 * @param sendType  the value for TMESSAGE.FS_SENDTYPE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setSendType(String sendType) {
		this.sendType = sendType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FS_MSGHEAD
	 * @return  the value of TMESSAGE.FS_MSGHEAD
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public String getMsgHead() {
		return msgHead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FS_MSGHEAD
	 * @param msgHead  the value for TMESSAGE.FS_MSGHEAD
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setMsgHead(String msgHead) {
		this.msgHead = msgHead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FS_MSGTEXT
	 * @return  the value of TMESSAGE.FS_MSGTEXT
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public String getMsgText() {
		return msgText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FS_MSGTEXT
	 * @param msgText  the value for TMESSAGE.FS_MSGTEXT
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setMsgText(String msgText) {
		this.msgText = msgText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FS_SENDID
	 * @return  the value of TMESSAGE.FS_SENDID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public String getSendid() {
		return sendid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FS_SENDID
	 * @param sendid  the value for TMESSAGE.FS_SENDID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setSendid(String sendid) {
		this.sendid = sendid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FS_RECVID
	 * @return  the value of TMESSAGE.FS_RECVID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public String getRecvid() {
		return recvid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FS_RECVID
	 * @param recvid  the value for TMESSAGE.FS_RECVID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setRecvid(String recvid) {
		this.recvid = recvid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FS_SUBID
	 * @return  the value of TMESSAGE.FS_SUBID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public String getSubid() {
		return subid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FS_SUBID
	 * @param subid  the value for TMESSAGE.FS_SUBID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setSubid(String subid) {
		this.subid = subid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FT_MSGDATE
	 * @return  the value of TMESSAGE.FT_MSGDATE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public Date getMsgDate() {
		return msgDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FT_MSGDATE
	 * @param msgDate  the value for TMESSAGE.FT_MSGDATE
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setMsgDate(Date msgDate) {
		this.msgDate = msgDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FI_MSGSTAT
	 * @return  the value of TMESSAGE.FI_MSGSTAT
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public String getMsgStat() {
		return MsgStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FI_MSGSTAT
	 * @param MsgStat  the value for TMESSAGE.FI_MSGSTAT
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setMsgStat(String MsgStat) {
		this.MsgStat = MsgStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FS_AUTHID
	 * @return  the value of TMESSAGE.FS_AUTHID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public String getAuthid() {
		return authid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FS_AUTHID
	 * @param authid  the value for TMESSAGE.FS_AUTHID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setAuthid(String authid) {
		this.authid = authid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TMESSAGE.FS_ID
	 * @return  the value of TMESSAGE.FS_ID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public String getFsId() {
		return fsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TMESSAGE.FS_ID
	 * @param fsId  the value for TMESSAGE.FS_ID
	 * @mbggenerated  Fri May 13 16:22:07 CST 2016
	 */
	public void setFsId(String fsId) {
		this.fsId = fsId;
	}
}