package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class RegionMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TREGIONMAP.FS_NO
     *
     * @mbggenerated
     */
    private String fsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TREGIONMAP.FS_NAME
     *
     * @mbggenerated
     */
    private String fsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TREGIONMAP.FS_MANAGENO
     *
     * @mbggenerated
     */
    private String fsManageno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TREGIONMAP.FI_LVL
     *
     * @mbggenerated
     */
    private BigDecimal fiLvl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TREGIONMAP.FS_NO
     *
     * @return the value of TREGIONMAP.FS_NO
     *
     * @mbggenerated
     */
    public String getFsNo() {
        return fsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TREGIONMAP.FS_NO
     *
     * @param fsNo the value for TREGIONMAP.FS_NO
     *
     * @mbggenerated
     */
    public void setFsNo(String fsNo) {
        this.fsNo = fsNo == null ? null : fsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TREGIONMAP.FS_NAME
     *
     * @return the value of TREGIONMAP.FS_NAME
     *
     * @mbggenerated
     */
    public String getFsName() {
        return fsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TREGIONMAP.FS_NAME
     *
     * @param fsName the value for TREGIONMAP.FS_NAME
     *
     * @mbggenerated
     */
    public void setFsName(String fsName) {
        this.fsName = fsName == null ? null : fsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TREGIONMAP.FS_MANAGENO
     *
     * @return the value of TREGIONMAP.FS_MANAGENO
     *
     * @mbggenerated
     */
    public String getFsManageno() {
        return fsManageno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TREGIONMAP.FS_MANAGENO
     *
     * @param fsManageno the value for TREGIONMAP.FS_MANAGENO
     *
     * @mbggenerated
     */
    public void setFsManageno(String fsManageno) {
        this.fsManageno = fsManageno == null ? null : fsManageno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TREGIONMAP.FI_LVL
     *
     * @return the value of TREGIONMAP.FI_LVL
     *
     * @mbggenerated
     */
    public BigDecimal getFiLvl() {
        return fiLvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TREGIONMAP.FI_LVL
     *
     * @param fiLvl the value for TREGIONMAP.FI_LVL
     *
     * @mbggenerated
     */
    public void setFiLvl(BigDecimal fiLvl) {
        this.fiLvl = fiLvl;
    }
}