package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class Scenic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENIC.FS_NO
     *
     * @mbggenerated
     */
    private String fsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENIC.FS_NAME
     *
     * @mbggenerated
     */
    private String fsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENIC.FS_REGIONNO
     *
     * @mbggenerated
     */
    private String fsRegionno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENIC.FS_ADDR
     *
     * @mbggenerated
     */
    private String fsAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENIC.FS_DESC
     *
     * @mbggenerated
     */
    private String fsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENIC.FS_LVL
     *
     * @mbggenerated
     */
    private String fsLvl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENIC.FS_OPENTIME
     *
     * @mbggenerated
     */
    private String fsOpentime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENIC.FS_SPECIALITY
     *
     * @mbggenerated
     */
    private String fsSpeciality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENIC.FI_STAT
     *
     * @mbggenerated
     */
    private BigDecimal fiStat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENIC.FS_NO
     *
     * @return the value of TSCENIC.FS_NO
     *
     * @mbggenerated
     */
    public String getFsNo() {
        return fsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENIC.FS_NO
     *
     * @param fsNo the value for TSCENIC.FS_NO
     *
     * @mbggenerated
     */
    public void setFsNo(String fsNo) {
        this.fsNo = fsNo == null ? null : fsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENIC.FS_NAME
     *
     * @return the value of TSCENIC.FS_NAME
     *
     * @mbggenerated
     */
    public String getFsName() {
        return fsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENIC.FS_NAME
     *
     * @param fsName the value for TSCENIC.FS_NAME
     *
     * @mbggenerated
     */
    public void setFsName(String fsName) {
        this.fsName = fsName == null ? null : fsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENIC.FS_REGIONNO
     *
     * @return the value of TSCENIC.FS_REGIONNO
     *
     * @mbggenerated
     */
    public String getFsRegionno() {
        return fsRegionno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENIC.FS_REGIONNO
     *
     * @param fsRegionno the value for TSCENIC.FS_REGIONNO
     *
     * @mbggenerated
     */
    public void setFsRegionno(String fsRegionno) {
        this.fsRegionno = fsRegionno == null ? null : fsRegionno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENIC.FS_ADDR
     *
     * @return the value of TSCENIC.FS_ADDR
     *
     * @mbggenerated
     */
    public String getFsAddr() {
        return fsAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENIC.FS_ADDR
     *
     * @param fsAddr the value for TSCENIC.FS_ADDR
     *
     * @mbggenerated
     */
    public void setFsAddr(String fsAddr) {
        this.fsAddr = fsAddr == null ? null : fsAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENIC.FS_DESC
     *
     * @return the value of TSCENIC.FS_DESC
     *
     * @mbggenerated
     */
    public String getFsDesc() {
        return fsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENIC.FS_DESC
     *
     * @param fsDesc the value for TSCENIC.FS_DESC
     *
     * @mbggenerated
     */
    public void setFsDesc(String fsDesc) {
        this.fsDesc = fsDesc == null ? null : fsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENIC.FS_LVL
     *
     * @return the value of TSCENIC.FS_LVL
     *
     * @mbggenerated
     */
    public String getFsLvl() {
        return fsLvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENIC.FS_LVL
     *
     * @param fsLvl the value for TSCENIC.FS_LVL
     *
     * @mbggenerated
     */
    public void setFsLvl(String fsLvl) {
        this.fsLvl = fsLvl == null ? null : fsLvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENIC.FS_OPENTIME
     *
     * @return the value of TSCENIC.FS_OPENTIME
     *
     * @mbggenerated
     */
    public String getFsOpentime() {
        return fsOpentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENIC.FS_OPENTIME
     *
     * @param fsOpentime the value for TSCENIC.FS_OPENTIME
     *
     * @mbggenerated
     */
    public void setFsOpentime(String fsOpentime) {
        this.fsOpentime = fsOpentime == null ? null : fsOpentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENIC.FS_SPECIALITY
     *
     * @return the value of TSCENIC.FS_SPECIALITY
     *
     * @mbggenerated
     */
    public String getFsSpeciality() {
        return fsSpeciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENIC.FS_SPECIALITY
     *
     * @param fsSpeciality the value for TSCENIC.FS_SPECIALITY
     *
     * @mbggenerated
     */
    public void setFsSpeciality(String fsSpeciality) {
        this.fsSpeciality = fsSpeciality == null ? null : fsSpeciality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENIC.FI_STAT
     *
     * @return the value of TSCENIC.FI_STAT
     *
     * @mbggenerated
     */
    public BigDecimal getFiStat() {
        return fiStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENIC.FI_STAT
     *
     * @param fiStat the value for TSCENIC.FI_STAT
     *
     * @mbggenerated
     */
    public void setFiStat(BigDecimal fiStat) {
        this.fiStat = fiStat;
    }
}