package com.yttx.yttxps.model;

import java.util.Date;

public class TCCPriceKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TCCPRICE.FS_CCNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	private String fsCcno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TCCPRICE.FS_RESNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	private String fsResno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TCCPRICE.FS_RESTYPE
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	private String fsRestype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TCCPRICE.FT_DATE
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	private Date ftDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TCCPRICE.FS_CCNO
	 * @return  the value of TCCPRICE.FS_CCNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public String getFsCcno() {
		return fsCcno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TCCPRICE.FS_CCNO
	 * @param fsCcno  the value for TCCPRICE.FS_CCNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public void setFsCcno(String fsCcno) {
		this.fsCcno = fsCcno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TCCPRICE.FS_RESNO
	 * @return  the value of TCCPRICE.FS_RESNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public String getFsResno() {
		return fsResno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TCCPRICE.FS_RESNO
	 * @param fsResno  the value for TCCPRICE.FS_RESNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public void setFsResno(String fsResno) {
		this.fsResno = fsResno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TCCPRICE.FS_RESTYPE
	 * @return  the value of TCCPRICE.FS_RESTYPE
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public String getFsRestype() {
		return fsRestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TCCPRICE.FS_RESTYPE
	 * @param fsRestype  the value for TCCPRICE.FS_RESTYPE
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public void setFsRestype(String fsRestype) {
		this.fsRestype = fsRestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TCCPRICE.FT_DATE
	 * @return  the value of TCCPRICE.FT_DATE
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public Date getFtDate() {
		return ftDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TCCPRICE.FT_DATE
	 * @param ftDate  the value for TCCPRICE.FT_DATE
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public void setFtDate(Date ftDate) {
		this.ftDate = ftDate;
	}
}