package com.yttx.yttxps.model;

import java.math.BigDecimal;
import java.util.Date;

public class TCCPrice extends TCCPriceKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TCCPRICE.FT_ENDDATE
	 * @mbggenerated  Sun Jan 24 18:25:21 CST 2016
	 */
	private Date ftEnddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TCCPRICE.FD_PRICE
	 * @mbggenerated  Sun Jan 24 18:25:21 CST 2016
	 */
	private BigDecimal fdPrice;
	
	private String excuteCode;
	private String errorMsg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TCCPRICE.FT_ENDDATE
	 * @return  the value of TCCPRICE.FT_ENDDATE
	 * @mbggenerated  Sun Jan 24 18:25:21 CST 2016
	 */
	public Date getFtEnddate() {
		return ftEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TCCPRICE.FT_ENDDATE
	 * @param ftEnddate  the value for TCCPRICE.FT_ENDDATE
	 * @mbggenerated  Sun Jan 24 18:25:21 CST 2016
	 */
	public void setFtEnddate(Date ftEnddate) {
		this.ftEnddate = ftEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TCCPRICE.FD_PRICE
	 * @return  the value of TCCPRICE.FD_PRICE
	 * @mbggenerated  Sun Jan 24 18:25:21 CST 2016
	 */
	public BigDecimal getFdPrice() {
		return fdPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TCCPRICE.FD_PRICE
	 * @param fdPrice  the value for TCCPRICE.FD_PRICE
	 * @mbggenerated  Sun Jan 24 18:25:21 CST 2016
	 */
	public void setFdPrice(BigDecimal fdPrice) {
		this.fdPrice = fdPrice;
	}

	public String getExcuteCode() {
		return excuteCode;
	}

	public void setExcuteCode(String excuteCode) {
		this.excuteCode = excuteCode;
	}

	public String getErrorMsg() {
		return errorMsg;
	}

	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}
}