package com.yttx.yttxps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TCloselistExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public TCloselistExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andFsNoIsNull() {
			addCriterion("FS_NO is null");
			return (Criteria) this;
		}

		public Criteria andFsNoIsNotNull() {
			addCriterion("FS_NO is not null");
			return (Criteria) this;
		}

		public Criteria andFsNoEqualTo(String value) {
			addCriterion("FS_NO =", value, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoNotEqualTo(String value) {
			addCriterion("FS_NO <>", value, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoGreaterThan(String value) {
			addCriterion("FS_NO >", value, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoGreaterThanOrEqualTo(String value) {
			addCriterion("FS_NO >=", value, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoLessThan(String value) {
			addCriterion("FS_NO <", value, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoLessThanOrEqualTo(String value) {
			addCriterion("FS_NO <=", value, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoLike(String value) {
			addCriterion("FS_NO like", value, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoNotLike(String value) {
			addCriterion("FS_NO not like", value, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoIn(List<String> values) {
			addCriterion("FS_NO in", values, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoNotIn(List<String> values) {
			addCriterion("FS_NO not in", values, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoBetween(String value1, String value2) {
			addCriterion("FS_NO between", value1, value2, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsNoNotBetween(String value1, String value2) {
			addCriterion("FS_NO not between", value1, value2, "fsNo");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdIsNull() {
			addCriterion("FS_ROUTE_ID is null");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdIsNotNull() {
			addCriterion("FS_ROUTE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdEqualTo(String value) {
			addCriterion("FS_ROUTE_ID =", value, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdNotEqualTo(String value) {
			addCriterion("FS_ROUTE_ID <>", value, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdGreaterThan(String value) {
			addCriterion("FS_ROUTE_ID >", value, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdGreaterThanOrEqualTo(String value) {
			addCriterion("FS_ROUTE_ID >=", value, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdLessThan(String value) {
			addCriterion("FS_ROUTE_ID <", value, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdLessThanOrEqualTo(String value) {
			addCriterion("FS_ROUTE_ID <=", value, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdLike(String value) {
			addCriterion("FS_ROUTE_ID like", value, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdNotLike(String value) {
			addCriterion("FS_ROUTE_ID not like", value, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdIn(List<String> values) {
			addCriterion("FS_ROUTE_ID in", values, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdNotIn(List<String> values) {
			addCriterion("FS_ROUTE_ID not in", values, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdBetween(String value1, String value2) {
			addCriterion("FS_ROUTE_ID between", value1, value2, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRouteIdNotBetween(String value1, String value2) {
			addCriterion("FS_ROUTE_ID not between", value1, value2, "fsRouteId");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameIsNull() {
			addCriterion("FS_ROUTENAME is null");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameIsNotNull() {
			addCriterion("FS_ROUTENAME is not null");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameEqualTo(String value) {
			addCriterion("FS_ROUTENAME =", value, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameNotEqualTo(String value) {
			addCriterion("FS_ROUTENAME <>", value, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameGreaterThan(String value) {
			addCriterion("FS_ROUTENAME >", value, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameGreaterThanOrEqualTo(String value) {
			addCriterion("FS_ROUTENAME >=", value, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameLessThan(String value) {
			addCriterion("FS_ROUTENAME <", value, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameLessThanOrEqualTo(String value) {
			addCriterion("FS_ROUTENAME <=", value, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameLike(String value) {
			addCriterion("FS_ROUTENAME like", value, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameNotLike(String value) {
			addCriterion("FS_ROUTENAME not like", value, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameIn(List<String> values) {
			addCriterion("FS_ROUTENAME in", values, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameNotIn(List<String> values) {
			addCriterion("FS_ROUTENAME not in", values, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameBetween(String value1, String value2) {
			addCriterion("FS_ROUTENAME between", value1, value2, "fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsRoutenameNotBetween(String value1, String value2) {
			addCriterion("FS_ROUTENAME not between", value1, value2,
					"fsRoutename");
			return (Criteria) this;
		}

		public Criteria andFsNameIsNull() {
			addCriterion("FS_NAME is null");
			return (Criteria) this;
		}

		public Criteria andFsNameIsNotNull() {
			addCriterion("FS_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andFsNameEqualTo(String value) {
			addCriterion("FS_NAME =", value, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameNotEqualTo(String value) {
			addCriterion("FS_NAME <>", value, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameGreaterThan(String value) {
			addCriterion("FS_NAME >", value, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameGreaterThanOrEqualTo(String value) {
			addCriterion("FS_NAME >=", value, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameLessThan(String value) {
			addCriterion("FS_NAME <", value, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameLessThanOrEqualTo(String value) {
			addCriterion("FS_NAME <=", value, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameLike(String value) {
			addCriterion("FS_NAME like", value, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameNotLike(String value) {
			addCriterion("FS_NAME not like", value, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameIn(List<String> values) {
			addCriterion("FS_NAME in", values, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameNotIn(List<String> values) {
			addCriterion("FS_NAME not in", values, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameBetween(String value1, String value2) {
			addCriterion("FS_NAME between", value1, value2, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsNameNotBetween(String value1, String value2) {
			addCriterion("FS_NAME not between", value1, value2, "fsName");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdIsNull() {
			addCriterion("FS_ORDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdIsNotNull() {
			addCriterion("FS_ORDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdEqualTo(String value) {
			addCriterion("FS_ORDER_ID =", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdNotEqualTo(String value) {
			addCriterion("FS_ORDER_ID <>", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdGreaterThan(String value) {
			addCriterion("FS_ORDER_ID >", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("FS_ORDER_ID >=", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdLessThan(String value) {
			addCriterion("FS_ORDER_ID <", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdLessThanOrEqualTo(String value) {
			addCriterion("FS_ORDER_ID <=", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdLike(String value) {
			addCriterion("FS_ORDER_ID like", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdNotLike(String value) {
			addCriterion("FS_ORDER_ID not like", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdIn(List<String> values) {
			addCriterion("FS_ORDER_ID in", values, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdNotIn(List<String> values) {
			addCriterion("FS_ORDER_ID not in", values, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdBetween(String value1, String value2) {
			addCriterion("FS_ORDER_ID between", value1, value2, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdNotBetween(String value1, String value2) {
			addCriterion("FS_ORDER_ID not between", value1, value2, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdIsNull() {
			addCriterion("FS_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andFsUserIdIsNotNull() {
			addCriterion("FS_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andFsUserIdEqualTo(String value) {
			addCriterion("FS_USER_ID =", value, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdNotEqualTo(String value) {
			addCriterion("FS_USER_ID <>", value, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdGreaterThan(String value) {
			addCriterion("FS_USER_ID >", value, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("FS_USER_ID >=", value, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdLessThan(String value) {
			addCriterion("FS_USER_ID <", value, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdLessThanOrEqualTo(String value) {
			addCriterion("FS_USER_ID <=", value, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdLike(String value) {
			addCriterion("FS_USER_ID like", value, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdNotLike(String value) {
			addCriterion("FS_USER_ID not like", value, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdIn(List<String> values) {
			addCriterion("FS_USER_ID in", values, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdNotIn(List<String> values) {
			addCriterion("FS_USER_ID not in", values, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdBetween(String value1, String value2) {
			addCriterion("FS_USER_ID between", value1, value2, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserIdNotBetween(String value1, String value2) {
			addCriterion("FS_USER_ID not between", value1, value2, "fsUserId");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidIsNull() {
			addCriterion("FS_USER_SUBID is null");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidIsNotNull() {
			addCriterion("FS_USER_SUBID is not null");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidEqualTo(String value) {
			addCriterion("FS_USER_SUBID =", value, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidNotEqualTo(String value) {
			addCriterion("FS_USER_SUBID <>", value, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidGreaterThan(String value) {
			addCriterion("FS_USER_SUBID >", value, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidGreaterThanOrEqualTo(String value) {
			addCriterion("FS_USER_SUBID >=", value, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidLessThan(String value) {
			addCriterion("FS_USER_SUBID <", value, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidLessThanOrEqualTo(String value) {
			addCriterion("FS_USER_SUBID <=", value, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidLike(String value) {
			addCriterion("FS_USER_SUBID like", value, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidNotLike(String value) {
			addCriterion("FS_USER_SUBID not like", value, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidIn(List<String> values) {
			addCriterion("FS_USER_SUBID in", values, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidNotIn(List<String> values) {
			addCriterion("FS_USER_SUBID not in", values, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidBetween(String value1, String value2) {
			addCriterion("FS_USER_SUBID between", value1, value2, "fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsUserSubidNotBetween(String value1, String value2) {
			addCriterion("FS_USER_SUBID not between", value1, value2,
					"fsUserSubid");
			return (Criteria) this;
		}

		public Criteria andFsOperIdIsNull() {
			addCriterion("FS_OPER_ID is null");
			return (Criteria) this;
		}

		public Criteria andFsOperIdIsNotNull() {
			addCriterion("FS_OPER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andFsOperIdEqualTo(String value) {
			addCriterion("FS_OPER_ID =", value, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdNotEqualTo(String value) {
			addCriterion("FS_OPER_ID <>", value, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdGreaterThan(String value) {
			addCriterion("FS_OPER_ID >", value, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdGreaterThanOrEqualTo(String value) {
			addCriterion("FS_OPER_ID >=", value, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdLessThan(String value) {
			addCriterion("FS_OPER_ID <", value, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdLessThanOrEqualTo(String value) {
			addCriterion("FS_OPER_ID <=", value, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdLike(String value) {
			addCriterion("FS_OPER_ID like", value, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdNotLike(String value) {
			addCriterion("FS_OPER_ID not like", value, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdIn(List<String> values) {
			addCriterion("FS_OPER_ID in", values, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdNotIn(List<String> values) {
			addCriterion("FS_OPER_ID not in", values, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdBetween(String value1, String value2) {
			addCriterion("FS_OPER_ID between", value1, value2, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFsOperIdNotBetween(String value1, String value2) {
			addCriterion("FS_OPER_ID not between", value1, value2, "fsOperId");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateIsNull() {
			addCriterion("FT_CREATDATE is null");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateIsNotNull() {
			addCriterion("FT_CREATDATE is not null");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateEqualTo(Date value) {
			addCriterionForJDBCDate("FT_CREATDATE =", value, "ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateNotEqualTo(Date value) {
			addCriterionForJDBCDate("FT_CREATDATE <>", value, "ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateGreaterThan(Date value) {
			addCriterionForJDBCDate("FT_CREATDATE >", value, "ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("FT_CREATDATE >=", value, "ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateLessThan(Date value) {
			addCriterionForJDBCDate("FT_CREATDATE <", value, "ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("FT_CREATDATE <=", value, "ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateIn(List<Date> values) {
			addCriterionForJDBCDate("FT_CREATDATE in", values, "ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateNotIn(List<Date> values) {
			addCriterionForJDBCDate("FT_CREATDATE not in", values,
					"ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("FT_CREATDATE between", value1, value2,
					"ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFtCreatdateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("FT_CREATDATE not between", value1, value2,
					"ftCreatdate");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeIsNull() {
			addCriterion("FD_TOTALFEE is null");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeIsNotNull() {
			addCriterion("FD_TOTALFEE is not null");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeEqualTo(BigDecimal value) {
			addCriterion("FD_TOTALFEE =", value, "fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeNotEqualTo(BigDecimal value) {
			addCriterion("FD_TOTALFEE <>", value, "fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeGreaterThan(BigDecimal value) {
			addCriterion("FD_TOTALFEE >", value, "fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FD_TOTALFEE >=", value, "fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeLessThan(BigDecimal value) {
			addCriterion("FD_TOTALFEE <", value, "fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FD_TOTALFEE <=", value, "fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeIn(List<BigDecimal> values) {
			addCriterion("FD_TOTALFEE in", values, "fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeNotIn(List<BigDecimal> values) {
			addCriterion("FD_TOTALFEE not in", values, "fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FD_TOTALFEE between", value1, value2, "fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdTotalfeeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FD_TOTALFEE not between", value1, value2,
					"fdTotalfee");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtIsNull() {
			addCriterion("FD_PAIDAMT is null");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtIsNotNull() {
			addCriterion("FD_PAIDAMT is not null");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtEqualTo(BigDecimal value) {
			addCriterion("FD_PAIDAMT =", value, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtNotEqualTo(BigDecimal value) {
			addCriterion("FD_PAIDAMT <>", value, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtGreaterThan(BigDecimal value) {
			addCriterion("FD_PAIDAMT >", value, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FD_PAIDAMT >=", value, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtLessThan(BigDecimal value) {
			addCriterion("FD_PAIDAMT <", value, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FD_PAIDAMT <=", value, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtIn(List<BigDecimal> values) {
			addCriterion("FD_PAIDAMT in", values, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtNotIn(List<BigDecimal> values) {
			addCriterion("FD_PAIDAMT not in", values, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FD_PAIDAMT between", value1, value2, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdPaidamtNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FD_PAIDAMT not between", value1, value2, "fdPaidamt");
			return (Criteria) this;
		}

		public Criteria andFdAmtIsNull() {
			addCriterion("FD_AMT is null");
			return (Criteria) this;
		}

		public Criteria andFdAmtIsNotNull() {
			addCriterion("FD_AMT is not null");
			return (Criteria) this;
		}

		public Criteria andFdAmtEqualTo(BigDecimal value) {
			addCriterion("FD_AMT =", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtNotEqualTo(BigDecimal value) {
			addCriterion("FD_AMT <>", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtGreaterThan(BigDecimal value) {
			addCriterion("FD_AMT >", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FD_AMT >=", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtLessThan(BigDecimal value) {
			addCriterion("FD_AMT <", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FD_AMT <=", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtIn(List<BigDecimal> values) {
			addCriterion("FD_AMT in", values, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtNotIn(List<BigDecimal> values) {
			addCriterion("FD_AMT not in", values, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FD_AMT between", value1, value2, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FD_AMT not between", value1, value2, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFsRemarkIsNull() {
			addCriterion("FS_REMARK is null");
			return (Criteria) this;
		}

		public Criteria andFsRemarkIsNotNull() {
			addCriterion("FS_REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andFsRemarkEqualTo(String value) {
			addCriterion("FS_REMARK =", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkNotEqualTo(String value) {
			addCriterion("FS_REMARK <>", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkGreaterThan(String value) {
			addCriterion("FS_REMARK >", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("FS_REMARK >=", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkLessThan(String value) {
			addCriterion("FS_REMARK <", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkLessThanOrEqualTo(String value) {
			addCriterion("FS_REMARK <=", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkLike(String value) {
			addCriterion("FS_REMARK like", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkNotLike(String value) {
			addCriterion("FS_REMARK not like", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkIn(List<String> values) {
			addCriterion("FS_REMARK in", values, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkNotIn(List<String> values) {
			addCriterion("FS_REMARK not in", values, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkBetween(String value1, String value2) {
			addCriterion("FS_REMARK between", value1, value2, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkNotBetween(String value1, String value2) {
			addCriterion("FS_REMARK not between", value1, value2, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFiStatIsNull() {
			addCriterion("FI_STAT is null");
			return (Criteria) this;
		}

		public Criteria andFiStatIsNotNull() {
			addCriterion("FI_STAT is not null");
			return (Criteria) this;
		}

		public Criteria andFiStatEqualTo(BigDecimal value) {
			addCriterion("FI_STAT =", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatNotEqualTo(BigDecimal value) {
			addCriterion("FI_STAT <>", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatGreaterThan(BigDecimal value) {
			addCriterion("FI_STAT >", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_STAT >=", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatLessThan(BigDecimal value) {
			addCriterion("FI_STAT <", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_STAT <=", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatIn(List<BigDecimal> values) {
			addCriterion("FI_STAT in", values, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatNotIn(List<BigDecimal> values) {
			addCriterion("FI_STAT not in", values, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FI_STAT between", value1, value2, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FI_STAT not between", value1, value2, "fiStat");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TCLOSELIST
	 * @mbggenerated  Sun Jan 24 19:51:04 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TCLOSELIST
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 24 19:20:42 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}