package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class TEntertainment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FS_NO
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FS_NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FS_REGIONNO
     *
     * @mbggenerated
     */
    private String regionno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FS_ADDR
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FS_TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FS_DESC
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FS_LVL
     *
     * @mbggenerated
     */
    private String lvl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FS_OPENTIME
     *
     * @mbggenerated
     */
    private String opentime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_PICKUPPRICE
     *
     * @mbggenerated
     */
    private BigDecimal pickupprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_FULL_LOW_QP
     *
     * @mbggenerated
     */
    private BigDecimal fullLowQp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_HALF_LOW_QP
     *
     * @mbggenerated
     */
    private BigDecimal halfLowQp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_CHILD_LOW_QP
     *
     * @mbggenerated
     */
    private BigDecimal childLowQp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_FREE_LOW_QP
     *
     * @mbggenerated
     */
    private BigDecimal freeLowQp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_FULL_LOW_TP
     *
     * @mbggenerated
     */
    private BigDecimal fullLowTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_HALF_LOW_TP
     *
     * @mbggenerated
     */
    private BigDecimal halfLowTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_CHILD_LOW_TP
     *
     * @mbggenerated
     */
    private BigDecimal childLowTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_FREE_LOW_TP
     *
     * @mbggenerated
     */
    private BigDecimal freeLowTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_FULL_PEAK_QP
     *
     * @mbggenerated
     */
    private BigDecimal fullPeakQp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_HALF_PEAK_QP
     *
     * @mbggenerated
     */
    private BigDecimal halfPeakQp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_CHILD_PEAK_QP
     *
     * @mbggenerated
     */
    private BigDecimal childPeakQp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_FREE_PEAK_QP
     *
     * @mbggenerated
     */
    private BigDecimal freePeakQp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_FULL_PEAK_TP
     *
     * @mbggenerated
     */
    private BigDecimal fullPeakTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_HALF_PEAK_TP
     *
     * @mbggenerated
     */
    private BigDecimal halfPeakTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_CHILD_PEAK_TP
     *
     * @mbggenerated
     */
    private BigDecimal childPeakTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FD_FREE_PEAK_TP
     *
     * @mbggenerated
     */
    private BigDecimal freePeakTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TENTERTAINMENT.FI_STAT
     *
     * @mbggenerated
     */
    private BigDecimal stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FS_NO
     *
     * @return the value of TENTERTAINMENT.FS_NO
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FS_NO
     *
     * @param no the value for TENTERTAINMENT.FS_NO
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FS_NAME
     *
     * @return the value of TENTERTAINMENT.FS_NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FS_NAME
     *
     * @param name the value for TENTERTAINMENT.FS_NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FS_REGIONNO
     *
     * @return the value of TENTERTAINMENT.FS_REGIONNO
     *
     * @mbggenerated
     */
    public String getRegionno() {
        return regionno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FS_REGIONNO
     *
     * @param regionno the value for TENTERTAINMENT.FS_REGIONNO
     *
     * @mbggenerated
     */
    public void setRegionno(String regionno) {
        this.regionno = regionno == null ? null : regionno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FS_ADDR
     *
     * @return the value of TENTERTAINMENT.FS_ADDR
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FS_ADDR
     *
     * @param addr the value for TENTERTAINMENT.FS_ADDR
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FS_TYPE
     *
     * @return the value of TENTERTAINMENT.FS_TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FS_TYPE
     *
     * @param type the value for TENTERTAINMENT.FS_TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FS_DESC
     *
     * @return the value of TENTERTAINMENT.FS_DESC
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FS_DESC
     *
     * @param desc the value for TENTERTAINMENT.FS_DESC
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FS_LVL
     *
     * @return the value of TENTERTAINMENT.FS_LVL
     *
     * @mbggenerated
     */
    public String getLvl() {
        return lvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FS_LVL
     *
     * @param lvl the value for TENTERTAINMENT.FS_LVL
     *
     * @mbggenerated
     */
    public void setLvl(String lvl) {
        this.lvl = lvl == null ? null : lvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FS_OPENTIME
     *
     * @return the value of TENTERTAINMENT.FS_OPENTIME
     *
     * @mbggenerated
     */
    public String getOpentime() {
        return opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FS_OPENTIME
     *
     * @param opentime the value for TENTERTAINMENT.FS_OPENTIME
     *
     * @mbggenerated
     */
    public void setOpentime(String opentime) {
        this.opentime = opentime == null ? null : opentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_PICKUPPRICE
     *
     * @return the value of TENTERTAINMENT.FD_PICKUPPRICE
     *
     * @mbggenerated
     */
    public BigDecimal getPickupprice() {
        return pickupprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_PICKUPPRICE
     *
     * @param pickupprice the value for TENTERTAINMENT.FD_PICKUPPRICE
     *
     * @mbggenerated
     */
    public void setPickupprice(BigDecimal pickupprice) {
        this.pickupprice = pickupprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_FULL_LOW_QP
     *
     * @return the value of TENTERTAINMENT.FD_FULL_LOW_QP
     *
     * @mbggenerated
     */
    public BigDecimal getFullLowQp() {
        return fullLowQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_FULL_LOW_QP
     *
     * @param fullLowQp the value for TENTERTAINMENT.FD_FULL_LOW_QP
     *
     * @mbggenerated
     */
    public void setFullLowQp(BigDecimal fullLowQp) {
        this.fullLowQp = fullLowQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_HALF_LOW_QP
     *
     * @return the value of TENTERTAINMENT.FD_HALF_LOW_QP
     *
     * @mbggenerated
     */
    public BigDecimal getHalfLowQp() {
        return halfLowQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_HALF_LOW_QP
     *
     * @param halfLowQp the value for TENTERTAINMENT.FD_HALF_LOW_QP
     *
     * @mbggenerated
     */
    public void setHalfLowQp(BigDecimal halfLowQp) {
        this.halfLowQp = halfLowQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_CHILD_LOW_QP
     *
     * @return the value of TENTERTAINMENT.FD_CHILD_LOW_QP
     *
     * @mbggenerated
     */
    public BigDecimal getChildLowQp() {
        return childLowQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_CHILD_LOW_QP
     *
     * @param childLowQp the value for TENTERTAINMENT.FD_CHILD_LOW_QP
     *
     * @mbggenerated
     */
    public void setChildLowQp(BigDecimal childLowQp) {
        this.childLowQp = childLowQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_FREE_LOW_QP
     *
     * @return the value of TENTERTAINMENT.FD_FREE_LOW_QP
     *
     * @mbggenerated
     */
    public BigDecimal getFreeLowQp() {
        return freeLowQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_FREE_LOW_QP
     *
     * @param freeLowQp the value for TENTERTAINMENT.FD_FREE_LOW_QP
     *
     * @mbggenerated
     */
    public void setFreeLowQp(BigDecimal freeLowQp) {
        this.freeLowQp = freeLowQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_FULL_LOW_TP
     *
     * @return the value of TENTERTAINMENT.FD_FULL_LOW_TP
     *
     * @mbggenerated
     */
    public BigDecimal getFullLowTp() {
        return fullLowTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_FULL_LOW_TP
     *
     * @param fullLowTp the value for TENTERTAINMENT.FD_FULL_LOW_TP
     *
     * @mbggenerated
     */
    public void setFullLowTp(BigDecimal fullLowTp) {
        this.fullLowTp = fullLowTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_HALF_LOW_TP
     *
     * @return the value of TENTERTAINMENT.FD_HALF_LOW_TP
     *
     * @mbggenerated
     */
    public BigDecimal getHalfLowTp() {
        return halfLowTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_HALF_LOW_TP
     *
     * @param halfLowTp the value for TENTERTAINMENT.FD_HALF_LOW_TP
     *
     * @mbggenerated
     */
    public void setHalfLowTp(BigDecimal halfLowTp) {
        this.halfLowTp = halfLowTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_CHILD_LOW_TP
     *
     * @return the value of TENTERTAINMENT.FD_CHILD_LOW_TP
     *
     * @mbggenerated
     */
    public BigDecimal getChildLowTp() {
        return childLowTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_CHILD_LOW_TP
     *
     * @param childLowTp the value for TENTERTAINMENT.FD_CHILD_LOW_TP
     *
     * @mbggenerated
     */
    public void setChildLowTp(BigDecimal childLowTp) {
        this.childLowTp = childLowTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_FREE_LOW_TP
     *
     * @return the value of TENTERTAINMENT.FD_FREE_LOW_TP
     *
     * @mbggenerated
     */
    public BigDecimal getFreeLowTp() {
        return freeLowTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_FREE_LOW_TP
     *
     * @param freeLowTp the value for TENTERTAINMENT.FD_FREE_LOW_TP
     *
     * @mbggenerated
     */
    public void setFreeLowTp(BigDecimal freeLowTp) {
        this.freeLowTp = freeLowTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_FULL_PEAK_QP
     *
     * @return the value of TENTERTAINMENT.FD_FULL_PEAK_QP
     *
     * @mbggenerated
     */
    public BigDecimal getFullPeakQp() {
        return fullPeakQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_FULL_PEAK_QP
     *
     * @param fullPeakQp the value for TENTERTAINMENT.FD_FULL_PEAK_QP
     *
     * @mbggenerated
     */
    public void setFullPeakQp(BigDecimal fullPeakQp) {
        this.fullPeakQp = fullPeakQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_HALF_PEAK_QP
     *
     * @return the value of TENTERTAINMENT.FD_HALF_PEAK_QP
     *
     * @mbggenerated
     */
    public BigDecimal getHalfPeakQp() {
        return halfPeakQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_HALF_PEAK_QP
     *
     * @param halfPeakQp the value for TENTERTAINMENT.FD_HALF_PEAK_QP
     *
     * @mbggenerated
     */
    public void setHalfPeakQp(BigDecimal halfPeakQp) {
        this.halfPeakQp = halfPeakQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_CHILD_PEAK_QP
     *
     * @return the value of TENTERTAINMENT.FD_CHILD_PEAK_QP
     *
     * @mbggenerated
     */
    public BigDecimal getChildPeakQp() {
        return childPeakQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_CHILD_PEAK_QP
     *
     * @param childPeakQp the value for TENTERTAINMENT.FD_CHILD_PEAK_QP
     *
     * @mbggenerated
     */
    public void setChildPeakQp(BigDecimal childPeakQp) {
        this.childPeakQp = childPeakQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_FREE_PEAK_QP
     *
     * @return the value of TENTERTAINMENT.FD_FREE_PEAK_QP
     *
     * @mbggenerated
     */
    public BigDecimal getFreePeakQp() {
        return freePeakQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_FREE_PEAK_QP
     *
     * @param freePeakQp the value for TENTERTAINMENT.FD_FREE_PEAK_QP
     *
     * @mbggenerated
     */
    public void setFreePeakQp(BigDecimal freePeakQp) {
        this.freePeakQp = freePeakQp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_FULL_PEAK_TP
     *
     * @return the value of TENTERTAINMENT.FD_FULL_PEAK_TP
     *
     * @mbggenerated
     */
    public BigDecimal getFullPeakTp() {
        return fullPeakTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_FULL_PEAK_TP
     *
     * @param fullPeakTp the value for TENTERTAINMENT.FD_FULL_PEAK_TP
     *
     * @mbggenerated
     */
    public void setFullPeakTp(BigDecimal fullPeakTp) {
        this.fullPeakTp = fullPeakTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_HALF_PEAK_TP
     *
     * @return the value of TENTERTAINMENT.FD_HALF_PEAK_TP
     *
     * @mbggenerated
     */
    public BigDecimal getHalfPeakTp() {
        return halfPeakTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_HALF_PEAK_TP
     *
     * @param halfPeakTp the value for TENTERTAINMENT.FD_HALF_PEAK_TP
     *
     * @mbggenerated
     */
    public void setHalfPeakTp(BigDecimal halfPeakTp) {
        this.halfPeakTp = halfPeakTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_CHILD_PEAK_TP
     *
     * @return the value of TENTERTAINMENT.FD_CHILD_PEAK_TP
     *
     * @mbggenerated
     */
    public BigDecimal getChildPeakTp() {
        return childPeakTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_CHILD_PEAK_TP
     *
     * @param childPeakTp the value for TENTERTAINMENT.FD_CHILD_PEAK_TP
     *
     * @mbggenerated
     */
    public void setChildPeakTp(BigDecimal childPeakTp) {
        this.childPeakTp = childPeakTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FD_FREE_PEAK_TP
     *
     * @return the value of TENTERTAINMENT.FD_FREE_PEAK_TP
     *
     * @mbggenerated
     */
    public BigDecimal getFreePeakTp() {
        return freePeakTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FD_FREE_PEAK_TP
     *
     * @param freePeakTp the value for TENTERTAINMENT.FD_FREE_PEAK_TP
     *
     * @mbggenerated
     */
    public void setFreePeakTp(BigDecimal freePeakTp) {
        this.freePeakTp = freePeakTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TENTERTAINMENT.FI_STAT
     *
     * @return the value of TENTERTAINMENT.FI_STAT
     *
     * @mbggenerated
     */
    public BigDecimal getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TENTERTAINMENT.FI_STAT
     *
     * @param stat the value for TENTERTAINMENT.FI_STAT
     *
     * @mbggenerated
     */
    public void setStat(BigDecimal stat) {
        this.stat = stat;
    }
}