package com.yttx.yttxps.model;

import java.math.BigDecimal;
import java.util.Date;

public class Tguide {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FS_NO
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FS_NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FI_GENDER
     *
     * @mbggenerated
     */
    private BigDecimal gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FS_IDNO
     *
     * @mbggenerated
     */
    private String idno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FT_WORKDATE
     *
     * @mbggenerated
     */
    private Date workdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FS_CONTACTNO
     *
     * @mbggenerated
     */
    private String contactno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FS_MAINROUTE
     *
     * @mbggenerated
     */
    private String mainroute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FS_PREFERTEEM
     *
     * @mbggenerated
     */
    private String preferteem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FS_SPECIALITY
     *
     * @mbggenerated
     */
    private String speciality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FS_DESC
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FS_LVL
     *
     * @mbggenerated
     */
    private String lvl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FD_SALARY
     *
     * @mbggenerated
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FD_DAYSALE
     *
     * @mbggenerated
     */
    private BigDecimal daysale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FD_WEEKSALE
     *
     * @mbggenerated
     */
    private BigDecimal weeksale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FD_MONTHSALE
     *
     * @mbggenerated
     */
    private BigDecimal monthsale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TGUIDE.FI_STAT
     *
     * @mbggenerated
     */
    private BigDecimal stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FS_NO
     *
     * @return the value of TGUIDE.FS_NO
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FS_NO
     *
     * @param no the value for TGUIDE.FS_NO
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FS_NAME
     *
     * @return the value of TGUIDE.FS_NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FS_NAME
     *
     * @param name the value for TGUIDE.FS_NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FI_GENDER
     *
     * @return the value of TGUIDE.FI_GENDER
     *
     * @mbggenerated
     */
    public BigDecimal getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FI_GENDER
     *
     * @param gender the value for TGUIDE.FI_GENDER
     *
     * @mbggenerated
     */
    public void setGender(BigDecimal gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FS_IDNO
     *
     * @return the value of TGUIDE.FS_IDNO
     *
     * @mbggenerated
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FS_IDNO
     *
     * @param idno the value for TGUIDE.FS_IDNO
     *
     * @mbggenerated
     */
    public void setIdno(String idno) {
        this.idno = idno == null ? null : idno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FT_WORKDATE
     *
     * @return the value of TGUIDE.FT_WORKDATE
     *
     * @mbggenerated
     */
    public Date getWorkdate() {
        return workdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FT_WORKDATE
     *
     * @param workdate the value for TGUIDE.FT_WORKDATE
     *
     * @mbggenerated
     */
    public void setWorkdate(Date workdate) {
        this.workdate = workdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FS_CONTACTNO
     *
     * @return the value of TGUIDE.FS_CONTACTNO
     *
     * @mbggenerated
     */
    public String getContactno() {
        return contactno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FS_CONTACTNO
     *
     * @param contactno the value for TGUIDE.FS_CONTACTNO
     *
     * @mbggenerated
     */
    public void setContactno(String contactno) {
        this.contactno = contactno == null ? null : contactno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FS_MAINROUTE
     *
     * @return the value of TGUIDE.FS_MAINROUTE
     *
     * @mbggenerated
     */
    public String getMainroute() {
        return mainroute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FS_MAINROUTE
     *
     * @param mainroute the value for TGUIDE.FS_MAINROUTE
     *
     * @mbggenerated
     */
    public void setMainroute(String mainroute) {
        this.mainroute = mainroute == null ? null : mainroute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FS_PREFERTEEM
     *
     * @return the value of TGUIDE.FS_PREFERTEEM
     *
     * @mbggenerated
     */
    public String getPreferteem() {
        return preferteem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FS_PREFERTEEM
     *
     * @param preferteem the value for TGUIDE.FS_PREFERTEEM
     *
     * @mbggenerated
     */
    public void setPreferteem(String preferteem) {
        this.preferteem = preferteem == null ? null : preferteem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FS_SPECIALITY
     *
     * @return the value of TGUIDE.FS_SPECIALITY
     *
     * @mbggenerated
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FS_SPECIALITY
     *
     * @param speciality the value for TGUIDE.FS_SPECIALITY
     *
     * @mbggenerated
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality == null ? null : speciality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FS_DESC
     *
     * @return the value of TGUIDE.FS_DESC
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FS_DESC
     *
     * @param desc the value for TGUIDE.FS_DESC
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FS_LVL
     *
     * @return the value of TGUIDE.FS_LVL
     *
     * @mbggenerated
     */
    public String getLvl() {
        return lvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FS_LVL
     *
     * @param lvl the value for TGUIDE.FS_LVL
     *
     * @mbggenerated
     */
    public void setLvl(String lvl) {
        this.lvl = lvl == null ? null : lvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FD_SALARY
     *
     * @return the value of TGUIDE.FD_SALARY
     *
     * @mbggenerated
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FD_SALARY
     *
     * @param salary the value for TGUIDE.FD_SALARY
     *
     * @mbggenerated
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FD_DAYSALE
     *
     * @return the value of TGUIDE.FD_DAYSALE
     *
     * @mbggenerated
     */
    public BigDecimal getDaysale() {
        return daysale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FD_DAYSALE
     *
     * @param daysale the value for TGUIDE.FD_DAYSALE
     *
     * @mbggenerated
     */
    public void setDaysale(BigDecimal daysale) {
        this.daysale = daysale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FD_WEEKSALE
     *
     * @return the value of TGUIDE.FD_WEEKSALE
     *
     * @mbggenerated
     */
    public BigDecimal getWeeksale() {
        return weeksale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FD_WEEKSALE
     *
     * @param weeksale the value for TGUIDE.FD_WEEKSALE
     *
     * @mbggenerated
     */
    public void setWeeksale(BigDecimal weeksale) {
        this.weeksale = weeksale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FD_MONTHSALE
     *
     * @return the value of TGUIDE.FD_MONTHSALE
     *
     * @mbggenerated
     */
    public BigDecimal getMonthsale() {
        return monthsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FD_MONTHSALE
     *
     * @param monthsale the value for TGUIDE.FD_MONTHSALE
     *
     * @mbggenerated
     */
    public void setMonthsale(BigDecimal monthsale) {
        this.monthsale = monthsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TGUIDE.FI_STAT
     *
     * @return the value of TGUIDE.FI_STAT
     *
     * @mbggenerated
     */
    public BigDecimal getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TGUIDE.FI_STAT
     *
     * @param stat the value for TGUIDE.FI_STAT
     *
     * @mbggenerated
     */
    public void setStat(BigDecimal stat) {
        this.stat = stat;
    }
}