package com.yttx.yttxps.model;

public class TOrderlistWithBLOBs extends TOrderlist {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TORDERLIST.FC_SCHEDULE
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	private String fcSchedule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TORDERLIST.FC_RESSNAPSHOT
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	private String fcRessnapshot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	private String fcCommfuzzysnapshot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TORDERLIST.FC_COMMRESSNAPSHOT
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	private String fcCommressnapshot;

	private String regionname;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TORDERLIST.FC_SCHEDULE
	 * @return  the value of TORDERLIST.FC_SCHEDULE
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	public String getFcSchedule() {
		return fcSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TORDERLIST.FC_SCHEDULE
	 * @param fcSchedule  the value for TORDERLIST.FC_SCHEDULE
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	public void setFcSchedule(String fcSchedule) {
		this.fcSchedule = fcSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TORDERLIST.FC_RESSNAPSHOT
	 * @return  the value of TORDERLIST.FC_RESSNAPSHOT
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	public String getFcRessnapshot() {
		return fcRessnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TORDERLIST.FC_RESSNAPSHOT
	 * @param fcRessnapshot  the value for TORDERLIST.FC_RESSNAPSHOT
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	public void setFcRessnapshot(String fcRessnapshot) {
		this.fcRessnapshot = fcRessnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @return  the value of TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	public String getFcCommfuzzysnapshot() {
		return fcCommfuzzysnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @param fcCommfuzzysnapshot  the value for TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	public void setFcCommfuzzysnapshot(String fcCommfuzzysnapshot) {
		this.fcCommfuzzysnapshot = fcCommfuzzysnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TORDERLIST.FC_COMMRESSNAPSHOT
	 * @return  the value of TORDERLIST.FC_COMMRESSNAPSHOT
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	public String getFcCommressnapshot() {
		return fcCommressnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TORDERLIST.FC_COMMRESSNAPSHOT
	 * @param fcCommressnapshot  the value for TORDERLIST.FC_COMMRESSNAPSHOT
	 * @mbggenerated  Tue Feb 16 18:09:37 CST 2016
	 */
	public void setFcCommressnapshot(String fcCommressnapshot) {
		this.fcCommressnapshot = fcCommressnapshot;
	}

	public String getRegionname() {
		return regionname;
	}

	public void setRegionname(String regionname) {
		this.regionname = regionname;
	}
	
}