package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class TOrderCusListKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDERCUSLIST.FI_SEQ
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    private BigDecimal fiSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDERCUSLIST.FS_ORDER_ID
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    private String fsOrderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TORDERCUSLIST.FI_SEQ
     *
     * @return the value of TORDERCUSLIST.FI_SEQ
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public BigDecimal getFiSeq() {
        return fiSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TORDERCUSLIST.FI_SEQ
     *
     * @param fiSeq the value for TORDERCUSLIST.FI_SEQ
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public void setFiSeq(BigDecimal fiSeq) {
        this.fiSeq = fiSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TORDERCUSLIST.FS_ORDER_ID
     *
     * @return the value of TORDERCUSLIST.FS_ORDER_ID
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public String getFsOrderId() {
        return fsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TORDERCUSLIST.FS_ORDER_ID
     *
     * @param fsOrderId the value for TORDERCUSLIST.FS_ORDER_ID
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public void setFsOrderId(String fsOrderId) {
        this.fsOrderId = fsOrderId;
    }
}