package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class TOrderCusList extends TOrderCusListKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDERCUSLIST.FS_NAME
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    private String fsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDERCUSLIST.FS_IDTYPE
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    private String fsIdtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDERCUSLIST.FS_ID
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    private String fsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDERCUSLIST.FS_TEL
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    private String fsTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDERCUSLIST.FS_MARK
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    private String fsMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDERCUSLIST.FI_STAT
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    private BigDecimal fiStat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TORDERCUSLIST.FS_NAME
     *
     * @return the value of TORDERCUSLIST.FS_NAME
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public String getFsName() {
        return fsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TORDERCUSLIST.FS_NAME
     *
     * @param fsName the value for TORDERCUSLIST.FS_NAME
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public void setFsName(String fsName) {
        this.fsName = fsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TORDERCUSLIST.FS_IDTYPE
     *
     * @return the value of TORDERCUSLIST.FS_IDTYPE
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public String getFsIdtype() {
        return fsIdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TORDERCUSLIST.FS_IDTYPE
     *
     * @param fsIdtype the value for TORDERCUSLIST.FS_IDTYPE
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public void setFsIdtype(String fsIdtype) {
        this.fsIdtype = fsIdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TORDERCUSLIST.FS_ID
     *
     * @return the value of TORDERCUSLIST.FS_ID
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public String getFsId() {
        return fsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TORDERCUSLIST.FS_ID
     *
     * @param fsId the value for TORDERCUSLIST.FS_ID
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public void setFsId(String fsId) {
        this.fsId = fsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TORDERCUSLIST.FS_TEL
     *
     * @return the value of TORDERCUSLIST.FS_TEL
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public String getFsTel() {
        return fsTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TORDERCUSLIST.FS_TEL
     *
     * @param fsTel the value for TORDERCUSLIST.FS_TEL
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public void setFsTel(String fsTel) {
        this.fsTel = fsTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TORDERCUSLIST.FS_MARK
     *
     * @return the value of TORDERCUSLIST.FS_MARK
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public String getFsMark() {
        return fsMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TORDERCUSLIST.FS_MARK
     *
     * @param fsMark the value for TORDERCUSLIST.FS_MARK
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public void setFsMark(String fsMark) {
        this.fsMark = fsMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TORDERCUSLIST.FI_STAT
     *
     * @return the value of TORDERCUSLIST.FI_STAT
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public BigDecimal getFiStat() {
        return fiStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TORDERCUSLIST.FI_STAT
     *
     * @param fiStat the value for TORDERCUSLIST.FI_STAT
     *
     * @mbggenerated Mon Mar 21 14:58:05 CST 2016
     */
    public void setFiStat(BigDecimal fiStat) {
        this.fiStat = fiStat;
    }
}