package com.yttx.yttxps.model;

import java.util.List;

import com.yttx.yttxps.xml.bean.Body;

public class TOrderlistWithBLOBs extends TOrderlist {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TORDERLIST.FC_SCHEDULE
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	private String fcSchedule;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TORDERLIST.FC_RESSNAPSHOT
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	private String fcRessnapshot;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	private String fcCommfuzzysnapshot;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TORDERLIST.FC_COMMRESSNAPSHOT
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	private String fcCommressnapshot;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TORDERLIST.FC_SCHEDULE
	 * @return  the value of TORDERLIST.FC_SCHEDULE
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	public String getFcSchedule() {
		return fcSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TORDERLIST.FC_SCHEDULE
	 * @param fcSchedule  the value for TORDERLIST.FC_SCHEDULE
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	public void setFcSchedule(String fcSchedule) {
		this.fcSchedule = fcSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TORDERLIST.FC_RESSNAPSHOT
	 * @return  the value of TORDERLIST.FC_RESSNAPSHOT
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	public String getFcRessnapshot() {
		return fcRessnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TORDERLIST.FC_RESSNAPSHOT
	 * @param fcRessnapshot  the value for TORDERLIST.FC_RESSNAPSHOT
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	public void setFcRessnapshot(String fcRessnapshot) {
		this.fcRessnapshot = fcRessnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @return  the value of TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	public String getFcCommfuzzysnapshot() {
		return fcCommfuzzysnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @param fcCommfuzzysnapshot  the value for TORDERLIST.FC_COMMFUZZYSNAPSHOT
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	public void setFcCommfuzzysnapshot(String fcCommfuzzysnapshot) {
		this.fcCommfuzzysnapshot = fcCommfuzzysnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TORDERLIST.FC_COMMRESSNAPSHOT
	 * @return  the value of TORDERLIST.FC_COMMRESSNAPSHOT
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	public String getFcCommressnapshot() {
		return fcCommressnapshot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TORDERLIST.FC_COMMRESSNAPSHOT
	 * @param fcCommressnapshot  the value for TORDERLIST.FC_COMMRESSNAPSHOT
	 * @mbggenerated  Thu Mar 10 17:09:19 CST 2016
	 */
	public void setFcCommressnapshot(String fcCommressnapshot) {
		this.fcCommressnapshot = fcCommressnapshot;
	}

	private String regionname;
	
	//预估行程Body，用于保存客户询价内容（用于定制线路订单）
	private Body scheduleBody;
	
	//定制公共精确资源快照（暂用于定制线路）
	private Body commBody;
	
	//批次精确资源快照（暂用于定制线路）
	private List<Body> batchBody;
	
	public String getRegionname() {
		return regionname;
	}

	public void setRegionname(String regionname) {
		this.regionname = regionname;
	}

	public Body getScheduleBody() {
		return scheduleBody;
	}

	public void setScheduleBody(Body scheduleBody) {
		this.scheduleBody = scheduleBody;
	}

	public Body getCommBody() {
		return commBody;
	}

	public void setCommBody(Body commBody) {
		this.commBody = commBody;
	}

	public List<Body> getBatchBody() {
		return batchBody;
	}

	public void setBatchBody(List<Body> batchBody) {
		this.batchBody = batchBody;
	}

}