package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class TResourceScenic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRESOURCESCENIC.FI_INDEX
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    private BigDecimal fiIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRESOURCESCENIC.FS_SCENICNO
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    private String fsScenicno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRESOURCESCENIC.FS_RESTYPE
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    private String fsRestype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRESOURCESCENIC.FS_RESNO
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    private String fsResno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRESOURCESCENIC.FI_INDEX
     *
     * @return the value of TRESOURCESCENIC.FI_INDEX
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    public BigDecimal getFiIndex() {
        return fiIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRESOURCESCENIC.FI_INDEX
     *
     * @param fiIndex the value for TRESOURCESCENIC.FI_INDEX
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    public void setFiIndex(BigDecimal fiIndex) {
        this.fiIndex = fiIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRESOURCESCENIC.FS_SCENICNO
     *
     * @return the value of TRESOURCESCENIC.FS_SCENICNO
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    public String getFsScenicno() {
        return fsScenicno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRESOURCESCENIC.FS_SCENICNO
     *
     * @param fsScenicno the value for TRESOURCESCENIC.FS_SCENICNO
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    public void setFsScenicno(String fsScenicno) {
        this.fsScenicno = fsScenicno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRESOURCESCENIC.FS_RESTYPE
     *
     * @return the value of TRESOURCESCENIC.FS_RESTYPE
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    public String getFsRestype() {
        return fsRestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRESOURCESCENIC.FS_RESTYPE
     *
     * @param fsRestype the value for TRESOURCESCENIC.FS_RESTYPE
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    public void setFsRestype(String fsRestype) {
        this.fsRestype = fsRestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRESOURCESCENIC.FS_RESNO
     *
     * @return the value of TRESOURCESCENIC.FS_RESNO
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    public String getFsResno() {
        return fsResno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRESOURCESCENIC.FS_RESNO
     *
     * @param fsResno the value for TRESOURCESCENIC.FS_RESNO
     *
     * @mbggenerated Sat Jan 16 11:00:29 CST 2016
     */
    public void setFsResno(String fsResno) {
        this.fsResno = fsResno;
    }
}