package com.yttx.yttxps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TrlistExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public TrlistExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andFiTrseqIsNull() {
			addCriterion("FI_TRSEQ is null");
			return (Criteria) this;
		}

		public Criteria andFiTrseqIsNotNull() {
			addCriterion("FI_TRSEQ is not null");
			return (Criteria) this;
		}

		public Criteria andFiTrseqEqualTo(BigDecimal value) {
			addCriterion("FI_TRSEQ =", value, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFiTrseqNotEqualTo(BigDecimal value) {
			addCriterion("FI_TRSEQ <>", value, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFiTrseqGreaterThan(BigDecimal value) {
			addCriterion("FI_TRSEQ >", value, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFiTrseqGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_TRSEQ >=", value, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFiTrseqLessThan(BigDecimal value) {
			addCriterion("FI_TRSEQ <", value, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFiTrseqLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_TRSEQ <=", value, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFiTrseqIn(List<BigDecimal> values) {
			addCriterion("FI_TRSEQ in", values, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFiTrseqNotIn(List<BigDecimal> values) {
			addCriterion("FI_TRSEQ not in", values, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFiTrseqBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FI_TRSEQ between", value1, value2, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFiTrseqNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FI_TRSEQ not between", value1, value2, "fiTrseq");
			return (Criteria) this;
		}

		public Criteria andFtDateIsNull() {
			addCriterion("FT_DATE is null");
			return (Criteria) this;
		}

		public Criteria andFtDateIsNotNull() {
			addCriterion("FT_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andFtDateEqualTo(Date value) {
			addCriterionForJDBCDate("FT_DATE =", value, "ftDate");
			return (Criteria) this;
		}

		public Criteria andFtDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("FT_DATE <>", value, "ftDate");
			return (Criteria) this;
		}

		public Criteria andFtDateGreaterThan(Date value) {
			addCriterionForJDBCDate("FT_DATE >", value, "ftDate");
			return (Criteria) this;
		}

		public Criteria andFtDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("FT_DATE >=", value, "ftDate");
			return (Criteria) this;
		}

		public Criteria andFtDateLessThan(Date value) {
			addCriterionForJDBCDate("FT_DATE <", value, "ftDate");
			return (Criteria) this;
		}

		public Criteria andFtDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("FT_DATE <=", value, "ftDate");
			return (Criteria) this;
		}

		public Criteria andFtDateIn(List<Date> values) {
			addCriterionForJDBCDate("FT_DATE in", values, "ftDate");
			return (Criteria) this;
		}

		public Criteria andFtDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("FT_DATE not in", values, "ftDate");
			return (Criteria) this;
		}

		public Criteria andFtDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("FT_DATE between", value1, value2, "ftDate");
			return (Criteria) this;
		}

		public Criteria andFtDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("FT_DATE not between", value1, value2,
					"ftDate");
			return (Criteria) this;
		}

		public Criteria andFsUseridIsNull() {
			addCriterion("FS_USERID is null");
			return (Criteria) this;
		}

		public Criteria andFsUseridIsNotNull() {
			addCriterion("FS_USERID is not null");
			return (Criteria) this;
		}

		public Criteria andFsUseridEqualTo(String value) {
			addCriterion("FS_USERID =", value, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridNotEqualTo(String value) {
			addCriterion("FS_USERID <>", value, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridGreaterThan(String value) {
			addCriterion("FS_USERID >", value, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridGreaterThanOrEqualTo(String value) {
			addCriterion("FS_USERID >=", value, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridLessThan(String value) {
			addCriterion("FS_USERID <", value, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridLessThanOrEqualTo(String value) {
			addCriterion("FS_USERID <=", value, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridLike(String value) {
			addCriterion("FS_USERID like", value, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridNotLike(String value) {
			addCriterion("FS_USERID not like", value, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridIn(List<String> values) {
			addCriterion("FS_USERID in", values, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridNotIn(List<String> values) {
			addCriterion("FS_USERID not in", values, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridBetween(String value1, String value2) {
			addCriterion("FS_USERID between", value1, value2, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsUseridNotBetween(String value1, String value2) {
			addCriterion("FS_USERID not between", value1, value2, "fsUserid");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeIsNull() {
			addCriterion("FS_TRCODE is null");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeIsNotNull() {
			addCriterion("FS_TRCODE is not null");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeEqualTo(String value) {
			addCriterion("FS_TRCODE =", value, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeNotEqualTo(String value) {
			addCriterion("FS_TRCODE <>", value, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeGreaterThan(String value) {
			addCriterion("FS_TRCODE >", value, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeGreaterThanOrEqualTo(String value) {
			addCriterion("FS_TRCODE >=", value, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeLessThan(String value) {
			addCriterion("FS_TRCODE <", value, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeLessThanOrEqualTo(String value) {
			addCriterion("FS_TRCODE <=", value, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeLike(String value) {
			addCriterion("FS_TRCODE like", value, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeNotLike(String value) {
			addCriterion("FS_TRCODE not like", value, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeIn(List<String> values) {
			addCriterion("FS_TRCODE in", values, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeNotIn(List<String> values) {
			addCriterion("FS_TRCODE not in", values, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeBetween(String value1, String value2) {
			addCriterion("FS_TRCODE between", value1, value2, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsTrcodeNotBetween(String value1, String value2) {
			addCriterion("FS_TRCODE not between", value1, value2, "fsTrcode");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdIsNull() {
			addCriterion("FS_ORDER_ID is null");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdIsNotNull() {
			addCriterion("FS_ORDER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdEqualTo(String value) {
			addCriterion("FS_ORDER_ID =", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdNotEqualTo(String value) {
			addCriterion("FS_ORDER_ID <>", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdGreaterThan(String value) {
			addCriterion("FS_ORDER_ID >", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("FS_ORDER_ID >=", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdLessThan(String value) {
			addCriterion("FS_ORDER_ID <", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdLessThanOrEqualTo(String value) {
			addCriterion("FS_ORDER_ID <=", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdLike(String value) {
			addCriterion("FS_ORDER_ID like", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdNotLike(String value) {
			addCriterion("FS_ORDER_ID not like", value, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdIn(List<String> values) {
			addCriterion("FS_ORDER_ID in", values, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdNotIn(List<String> values) {
			addCriterion("FS_ORDER_ID not in", values, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdBetween(String value1, String value2) {
			addCriterion("FS_ORDER_ID between", value1, value2, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFsOrderIdNotBetween(String value1, String value2) {
			addCriterion("FS_ORDER_ID not between", value1, value2, "fsOrderId");
			return (Criteria) this;
		}

		public Criteria andFiSeqIsNull() {
			addCriterion("FI_SEQ is null");
			return (Criteria) this;
		}

		public Criteria andFiSeqIsNotNull() {
			addCriterion("FI_SEQ is not null");
			return (Criteria) this;
		}

		public Criteria andFiSeqEqualTo(BigDecimal value) {
			addCriterion("FI_SEQ =", value, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFiSeqNotEqualTo(BigDecimal value) {
			addCriterion("FI_SEQ <>", value, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFiSeqGreaterThan(BigDecimal value) {
			addCriterion("FI_SEQ >", value, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFiSeqGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_SEQ >=", value, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFiSeqLessThan(BigDecimal value) {
			addCriterion("FI_SEQ <", value, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFiSeqLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_SEQ <=", value, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFiSeqIn(List<BigDecimal> values) {
			addCriterion("FI_SEQ in", values, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFiSeqNotIn(List<BigDecimal> values) {
			addCriterion("FI_SEQ not in", values, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFiSeqBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FI_SEQ between", value1, value2, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFiSeqNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FI_SEQ not between", value1, value2, "fiSeq");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdIsNull() {
			addCriterion("FS_CLOSE_ID is null");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdIsNotNull() {
			addCriterion("FS_CLOSE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdEqualTo(String value) {
			addCriterion("FS_CLOSE_ID =", value, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdNotEqualTo(String value) {
			addCriterion("FS_CLOSE_ID <>", value, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdGreaterThan(String value) {
			addCriterion("FS_CLOSE_ID >", value, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdGreaterThanOrEqualTo(String value) {
			addCriterion("FS_CLOSE_ID >=", value, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdLessThan(String value) {
			addCriterion("FS_CLOSE_ID <", value, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdLessThanOrEqualTo(String value) {
			addCriterion("FS_CLOSE_ID <=", value, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdLike(String value) {
			addCriterion("FS_CLOSE_ID like", value, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdNotLike(String value) {
			addCriterion("FS_CLOSE_ID not like", value, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdIn(List<String> values) {
			addCriterion("FS_CLOSE_ID in", values, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdNotIn(List<String> values) {
			addCriterion("FS_CLOSE_ID not in", values, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdBetween(String value1, String value2) {
			addCriterion("FS_CLOSE_ID between", value1, value2, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFsCloseIdNotBetween(String value1, String value2) {
			addCriterion("FS_CLOSE_ID not between", value1, value2, "fsCloseId");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeIsNull() {
			addCriterion("FI_TRTYPE is null");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeIsNotNull() {
			addCriterion("FI_TRTYPE is not null");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeEqualTo(BigDecimal value) {
			addCriterion("FI_TRTYPE =", value, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeNotEqualTo(BigDecimal value) {
			addCriterion("FI_TRTYPE <>", value, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeGreaterThan(BigDecimal value) {
			addCriterion("FI_TRTYPE >", value, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_TRTYPE >=", value, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeLessThan(BigDecimal value) {
			addCriterion("FI_TRTYPE <", value, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_TRTYPE <=", value, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeIn(List<BigDecimal> values) {
			addCriterion("FI_TRTYPE in", values, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeNotIn(List<BigDecimal> values) {
			addCriterion("FI_TRTYPE not in", values, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FI_TRTYPE between", value1, value2, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFiTrtypeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("FI_TRTYPE not between", value1, value2, "fiTrtype");
			return (Criteria) this;
		}

		public Criteria andFdAmtIsNull() {
			addCriterion("FD_AMT is null");
			return (Criteria) this;
		}

		public Criteria andFdAmtIsNotNull() {
			addCriterion("FD_AMT is not null");
			return (Criteria) this;
		}

		public Criteria andFdAmtEqualTo(BigDecimal value) {
			addCriterion("FD_AMT =", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtNotEqualTo(BigDecimal value) {
			addCriterion("FD_AMT <>", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtGreaterThan(BigDecimal value) {
			addCriterion("FD_AMT >", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FD_AMT >=", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtLessThan(BigDecimal value) {
			addCriterion("FD_AMT <", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FD_AMT <=", value, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtIn(List<BigDecimal> values) {
			addCriterion("FD_AMT in", values, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtNotIn(List<BigDecimal> values) {
			addCriterion("FD_AMT not in", values, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FD_AMT between", value1, value2, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFdAmtNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FD_AMT not between", value1, value2, "fdAmt");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelIsNull() {
			addCriterion("FS_TRCHANNEL is null");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelIsNotNull() {
			addCriterion("FS_TRCHANNEL is not null");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelEqualTo(String value) {
			addCriterion("FS_TRCHANNEL =", value, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelNotEqualTo(String value) {
			addCriterion("FS_TRCHANNEL <>", value, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelGreaterThan(String value) {
			addCriterion("FS_TRCHANNEL >", value, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelGreaterThanOrEqualTo(String value) {
			addCriterion("FS_TRCHANNEL >=", value, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelLessThan(String value) {
			addCriterion("FS_TRCHANNEL <", value, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelLessThanOrEqualTo(String value) {
			addCriterion("FS_TRCHANNEL <=", value, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelLike(String value) {
			addCriterion("FS_TRCHANNEL like", value, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelNotLike(String value) {
			addCriterion("FS_TRCHANNEL not like", value, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelIn(List<String> values) {
			addCriterion("FS_TRCHANNEL in", values, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelNotIn(List<String> values) {
			addCriterion("FS_TRCHANNEL not in", values, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelBetween(String value1, String value2) {
			addCriterion("FS_TRCHANNEL between", value1, value2, "fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsTrchannelNotBetween(String value1, String value2) {
			addCriterion("FS_TRCHANNEL not between", value1, value2,
					"fsTrchannel");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoIsNull() {
			addCriterion("FS_ENTSEQNO is null");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoIsNotNull() {
			addCriterion("FS_ENTSEQNO is not null");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoEqualTo(String value) {
			addCriterion("FS_ENTSEQNO =", value, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoNotEqualTo(String value) {
			addCriterion("FS_ENTSEQNO <>", value, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoGreaterThan(String value) {
			addCriterion("FS_ENTSEQNO >", value, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoGreaterThanOrEqualTo(String value) {
			addCriterion("FS_ENTSEQNO >=", value, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoLessThan(String value) {
			addCriterion("FS_ENTSEQNO <", value, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoLessThanOrEqualTo(String value) {
			addCriterion("FS_ENTSEQNO <=", value, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoLike(String value) {
			addCriterion("FS_ENTSEQNO like", value, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoNotLike(String value) {
			addCriterion("FS_ENTSEQNO not like", value, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoIn(List<String> values) {
			addCriterion("FS_ENTSEQNO in", values, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoNotIn(List<String> values) {
			addCriterion("FS_ENTSEQNO not in", values, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoBetween(String value1, String value2) {
			addCriterion("FS_ENTSEQNO between", value1, value2, "fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFsEntseqnoNotBetween(String value1, String value2) {
			addCriterion("FS_ENTSEQNO not between", value1, value2,
					"fsEntseqno");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateIsNull() {
			addCriterion("FT_ENTACTDATE is null");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateIsNotNull() {
			addCriterion("FT_ENTACTDATE is not null");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateEqualTo(Date value) {
			addCriterionForJDBCDate("FT_ENTACTDATE =", value, "ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateNotEqualTo(Date value) {
			addCriterionForJDBCDate("FT_ENTACTDATE <>", value, "ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateGreaterThan(Date value) {
			addCriterionForJDBCDate("FT_ENTACTDATE >", value, "ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("FT_ENTACTDATE >=", value, "ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateLessThan(Date value) {
			addCriterionForJDBCDate("FT_ENTACTDATE <", value, "ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("FT_ENTACTDATE <=", value, "ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateIn(List<Date> values) {
			addCriterionForJDBCDate("FT_ENTACTDATE in", values, "ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateNotIn(List<Date> values) {
			addCriterionForJDBCDate("FT_ENTACTDATE not in", values,
					"ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("FT_ENTACTDATE between", value1, value2,
					"ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFtEntactdateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("FT_ENTACTDATE not between", value1,
					value2, "ftEntactdate");
			return (Criteria) this;
		}

		public Criteria andFsIndexIsNull() {
			addCriterion("FS_INDEX is null");
			return (Criteria) this;
		}

		public Criteria andFsIndexIsNotNull() {
			addCriterion("FS_INDEX is not null");
			return (Criteria) this;
		}

		public Criteria andFsIndexEqualTo(String value) {
			addCriterion("FS_INDEX =", value, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexNotEqualTo(String value) {
			addCriterion("FS_INDEX <>", value, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexGreaterThan(String value) {
			addCriterion("FS_INDEX >", value, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexGreaterThanOrEqualTo(String value) {
			addCriterion("FS_INDEX >=", value, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexLessThan(String value) {
			addCriterion("FS_INDEX <", value, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexLessThanOrEqualTo(String value) {
			addCriterion("FS_INDEX <=", value, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexLike(String value) {
			addCriterion("FS_INDEX like", value, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexNotLike(String value) {
			addCriterion("FS_INDEX not like", value, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexIn(List<String> values) {
			addCriterion("FS_INDEX in", values, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexNotIn(List<String> values) {
			addCriterion("FS_INDEX not in", values, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexBetween(String value1, String value2) {
			addCriterion("FS_INDEX between", value1, value2, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsIndexNotBetween(String value1, String value2) {
			addCriterion("FS_INDEX not between", value1, value2, "fsIndex");
			return (Criteria) this;
		}

		public Criteria andFsRemarkIsNull() {
			addCriterion("FS_REMARK is null");
			return (Criteria) this;
		}

		public Criteria andFsRemarkIsNotNull() {
			addCriterion("FS_REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andFsRemarkEqualTo(String value) {
			addCriterion("FS_REMARK =", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkNotEqualTo(String value) {
			addCriterion("FS_REMARK <>", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkGreaterThan(String value) {
			addCriterion("FS_REMARK >", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("FS_REMARK >=", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkLessThan(String value) {
			addCriterion("FS_REMARK <", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkLessThanOrEqualTo(String value) {
			addCriterion("FS_REMARK <=", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkLike(String value) {
			addCriterion("FS_REMARK like", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkNotLike(String value) {
			addCriterion("FS_REMARK not like", value, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkIn(List<String> values) {
			addCriterion("FS_REMARK in", values, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkNotIn(List<String> values) {
			addCriterion("FS_REMARK not in", values, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkBetween(String value1, String value2) {
			addCriterion("FS_REMARK between", value1, value2, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRemarkNotBetween(String value1, String value2) {
			addCriterion("FS_REMARK not between", value1, value2, "fsRemark");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeIsNull() {
			addCriterion("FS_RETCODE is null");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeIsNotNull() {
			addCriterion("FS_RETCODE is not null");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeEqualTo(String value) {
			addCriterion("FS_RETCODE =", value, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeNotEqualTo(String value) {
			addCriterion("FS_RETCODE <>", value, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeGreaterThan(String value) {
			addCriterion("FS_RETCODE >", value, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeGreaterThanOrEqualTo(String value) {
			addCriterion("FS_RETCODE >=", value, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeLessThan(String value) {
			addCriterion("FS_RETCODE <", value, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeLessThanOrEqualTo(String value) {
			addCriterion("FS_RETCODE <=", value, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeLike(String value) {
			addCriterion("FS_RETCODE like", value, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeNotLike(String value) {
			addCriterion("FS_RETCODE not like", value, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeIn(List<String> values) {
			addCriterion("FS_RETCODE in", values, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeNotIn(List<String> values) {
			addCriterion("FS_RETCODE not in", values, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeBetween(String value1, String value2) {
			addCriterion("FS_RETCODE between", value1, value2, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetcodeNotBetween(String value1, String value2) {
			addCriterion("FS_RETCODE not between", value1, value2, "fsRetcode");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgIsNull() {
			addCriterion("FS_RETMSG is null");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgIsNotNull() {
			addCriterion("FS_RETMSG is not null");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgEqualTo(String value) {
			addCriterion("FS_RETMSG =", value, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgNotEqualTo(String value) {
			addCriterion("FS_RETMSG <>", value, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgGreaterThan(String value) {
			addCriterion("FS_RETMSG >", value, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgGreaterThanOrEqualTo(String value) {
			addCriterion("FS_RETMSG >=", value, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgLessThan(String value) {
			addCriterion("FS_RETMSG <", value, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgLessThanOrEqualTo(String value) {
			addCriterion("FS_RETMSG <=", value, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgLike(String value) {
			addCriterion("FS_RETMSG like", value, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgNotLike(String value) {
			addCriterion("FS_RETMSG not like", value, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgIn(List<String> values) {
			addCriterion("FS_RETMSG in", values, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgNotIn(List<String> values) {
			addCriterion("FS_RETMSG not in", values, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgBetween(String value1, String value2) {
			addCriterion("FS_RETMSG between", value1, value2, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFsRetmsgNotBetween(String value1, String value2) {
			addCriterion("FS_RETMSG not between", value1, value2, "fsRetmsg");
			return (Criteria) this;
		}

		public Criteria andFiStatIsNull() {
			addCriterion("FI_STAT is null");
			return (Criteria) this;
		}

		public Criteria andFiStatIsNotNull() {
			addCriterion("FI_STAT is not null");
			return (Criteria) this;
		}

		public Criteria andFiStatEqualTo(BigDecimal value) {
			addCriterion("FI_STAT =", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatNotEqualTo(BigDecimal value) {
			addCriterion("FI_STAT <>", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatGreaterThan(BigDecimal value) {
			addCriterion("FI_STAT >", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_STAT >=", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatLessThan(BigDecimal value) {
			addCriterion("FI_STAT <", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FI_STAT <=", value, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatIn(List<BigDecimal> values) {
			addCriterion("FI_STAT in", values, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatNotIn(List<BigDecimal> values) {
			addCriterion("FI_STAT not in", values, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FI_STAT between", value1, value2, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFiStatNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FI_STAT not between", value1, value2, "fiStat");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidIsNull() {
			addCriterion("FS_SYSOPERID is null");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidIsNotNull() {
			addCriterion("FS_SYSOPERID is not null");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidEqualTo(String value) {
			addCriterion("FS_SYSOPERID =", value, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidNotEqualTo(String value) {
			addCriterion("FS_SYSOPERID <>", value, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidGreaterThan(String value) {
			addCriterion("FS_SYSOPERID >", value, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidGreaterThanOrEqualTo(String value) {
			addCriterion("FS_SYSOPERID >=", value, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidLessThan(String value) {
			addCriterion("FS_SYSOPERID <", value, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidLessThanOrEqualTo(String value) {
			addCriterion("FS_SYSOPERID <=", value, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidLike(String value) {
			addCriterion("FS_SYSOPERID like", value, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidNotLike(String value) {
			addCriterion("FS_SYSOPERID not like", value, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidIn(List<String> values) {
			addCriterion("FS_SYSOPERID in", values, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidNotIn(List<String> values) {
			addCriterion("FS_SYSOPERID not in", values, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidBetween(String value1, String value2) {
			addCriterion("FS_SYSOPERID between", value1, value2, "fsSysoperid");
			return (Criteria) this;
		}

		public Criteria andFsSysoperidNotBetween(String value1, String value2) {
			addCriterion("FS_SYSOPERID not between", value1, value2,
					"fsSysoperid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TTRLIST
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TTRLIST
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 13 09:48:53 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}