package com.yttx.yttxps.model;

import java.math.BigDecimal;
import java.util.Date;

public class Trlist {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FI_TRSEQ
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private BigDecimal fiTrseq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FT_DATE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private Date ftDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_USERID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_TRCODE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsTrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_ORDER_ID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FI_SEQ
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private BigDecimal fiSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_CLOSE_ID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsCloseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FI_TRTYPE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private BigDecimal fiTrtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FD_AMT
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private BigDecimal fdAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_TRCHANNEL
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsTrchannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_ENTSEQNO
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsEntseqno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FT_ENTACTDATE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private Date ftEntactdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_INDEX
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_REMARK
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_RETCODE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsRetcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_RETMSG
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsRetmsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FI_STAT
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private BigDecimal fiStat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRLIST.FS_SYSOPERID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	private String fsSysoperid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FI_TRSEQ
	 * @return  the value of TTRLIST.FI_TRSEQ
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public BigDecimal getFiTrseq() {
		return fiTrseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FI_TRSEQ
	 * @param fiTrseq  the value for TTRLIST.FI_TRSEQ
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFiTrseq(BigDecimal fiTrseq) {
		this.fiTrseq = fiTrseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FT_DATE
	 * @return  the value of TTRLIST.FT_DATE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public Date getFtDate() {
		return ftDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FT_DATE
	 * @param ftDate  the value for TTRLIST.FT_DATE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFtDate(Date ftDate) {
		this.ftDate = ftDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_USERID
	 * @return  the value of TTRLIST.FS_USERID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsUserid() {
		return fsUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_USERID
	 * @param fsUserid  the value for TTRLIST.FS_USERID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsUserid(String fsUserid) {
		this.fsUserid = fsUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_TRCODE
	 * @return  the value of TTRLIST.FS_TRCODE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsTrcode() {
		return fsTrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_TRCODE
	 * @param fsTrcode  the value for TTRLIST.FS_TRCODE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsTrcode(String fsTrcode) {
		this.fsTrcode = fsTrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_ORDER_ID
	 * @return  the value of TTRLIST.FS_ORDER_ID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsOrderId() {
		return fsOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_ORDER_ID
	 * @param fsOrderId  the value for TTRLIST.FS_ORDER_ID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsOrderId(String fsOrderId) {
		this.fsOrderId = fsOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FI_SEQ
	 * @return  the value of TTRLIST.FI_SEQ
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public BigDecimal getFiSeq() {
		return fiSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FI_SEQ
	 * @param fiSeq  the value for TTRLIST.FI_SEQ
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFiSeq(BigDecimal fiSeq) {
		this.fiSeq = fiSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_CLOSE_ID
	 * @return  the value of TTRLIST.FS_CLOSE_ID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsCloseId() {
		return fsCloseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_CLOSE_ID
	 * @param fsCloseId  the value for TTRLIST.FS_CLOSE_ID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsCloseId(String fsCloseId) {
		this.fsCloseId = fsCloseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FI_TRTYPE
	 * @return  the value of TTRLIST.FI_TRTYPE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public BigDecimal getFiTrtype() {
		return fiTrtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FI_TRTYPE
	 * @param fiTrtype  the value for TTRLIST.FI_TRTYPE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFiTrtype(BigDecimal fiTrtype) {
		this.fiTrtype = fiTrtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FD_AMT
	 * @return  the value of TTRLIST.FD_AMT
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public BigDecimal getFdAmt() {
		return fdAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FD_AMT
	 * @param fdAmt  the value for TTRLIST.FD_AMT
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFdAmt(BigDecimal fdAmt) {
		this.fdAmt = fdAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_TRCHANNEL
	 * @return  the value of TTRLIST.FS_TRCHANNEL
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsTrchannel() {
		return fsTrchannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_TRCHANNEL
	 * @param fsTrchannel  the value for TTRLIST.FS_TRCHANNEL
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsTrchannel(String fsTrchannel) {
		this.fsTrchannel = fsTrchannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_ENTSEQNO
	 * @return  the value of TTRLIST.FS_ENTSEQNO
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsEntseqno() {
		return fsEntseqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_ENTSEQNO
	 * @param fsEntseqno  the value for TTRLIST.FS_ENTSEQNO
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsEntseqno(String fsEntseqno) {
		this.fsEntseqno = fsEntseqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FT_ENTACTDATE
	 * @return  the value of TTRLIST.FT_ENTACTDATE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public Date getFtEntactdate() {
		return ftEntactdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FT_ENTACTDATE
	 * @param ftEntactdate  the value for TTRLIST.FT_ENTACTDATE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFtEntactdate(Date ftEntactdate) {
		this.ftEntactdate = ftEntactdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_INDEX
	 * @return  the value of TTRLIST.FS_INDEX
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsIndex() {
		return fsIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_INDEX
	 * @param fsIndex  the value for TTRLIST.FS_INDEX
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsIndex(String fsIndex) {
		this.fsIndex = fsIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_REMARK
	 * @return  the value of TTRLIST.FS_REMARK
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsRemark() {
		return fsRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_REMARK
	 * @param fsRemark  the value for TTRLIST.FS_REMARK
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsRemark(String fsRemark) {
		this.fsRemark = fsRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_RETCODE
	 * @return  the value of TTRLIST.FS_RETCODE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsRetcode() {
		return fsRetcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_RETCODE
	 * @param fsRetcode  the value for TTRLIST.FS_RETCODE
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsRetcode(String fsRetcode) {
		this.fsRetcode = fsRetcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_RETMSG
	 * @return  the value of TTRLIST.FS_RETMSG
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsRetmsg() {
		return fsRetmsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_RETMSG
	 * @param fsRetmsg  the value for TTRLIST.FS_RETMSG
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsRetmsg(String fsRetmsg) {
		this.fsRetmsg = fsRetmsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FI_STAT
	 * @return  the value of TTRLIST.FI_STAT
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public BigDecimal getFiStat() {
		return fiStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FI_STAT
	 * @param fiStat  the value for TTRLIST.FI_STAT
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFiStat(BigDecimal fiStat) {
		this.fiStat = fiStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRLIST.FS_SYSOPERID
	 * @return  the value of TTRLIST.FS_SYSOPERID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public String getFsSysoperid() {
		return fsSysoperid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRLIST.FS_SYSOPERID
	 * @param fsSysoperid  the value for TTRLIST.FS_SYSOPERID
	 * @mbggenerated  Thu Apr 14 14:20:48 CST 2016
	 */
	public void setFsSysoperid(String fsSysoperid) {
		this.fsSysoperid = fsSysoperid;
	}
}