package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class TRouteCCKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTECC.FI_DAYFLAG
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	private BigDecimal fiDayflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTECC.FS_CCNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	private String fsCcno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTECC.FS_RESNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	private String fsResno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTECC.FS_RESTYPE
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	private String fsRestype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTECC.FS_ROUTENO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	private String fsRouteno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTECC.FI_DAYFLAG
	 * @return  the value of TROUTECC.FI_DAYFLAG
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public BigDecimal getFiDayflag() {
		return fiDayflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTECC.FI_DAYFLAG
	 * @param fiDayflag  the value for TROUTECC.FI_DAYFLAG
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public void setFiDayflag(BigDecimal fiDayflag) {
		this.fiDayflag = fiDayflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTECC.FS_CCNO
	 * @return  the value of TROUTECC.FS_CCNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public String getFsCcno() {
		return fsCcno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTECC.FS_CCNO
	 * @param fsCcno  the value for TROUTECC.FS_CCNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public void setFsCcno(String fsCcno) {
		this.fsCcno = fsCcno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTECC.FS_RESNO
	 * @return  the value of TROUTECC.FS_RESNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public String getFsResno() {
		return fsResno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTECC.FS_RESNO
	 * @param fsResno  the value for TROUTECC.FS_RESNO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public void setFsResno(String fsResno) {
		this.fsResno = fsResno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTECC.FS_RESTYPE
	 * @return  the value of TROUTECC.FS_RESTYPE
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public String getFsRestype() {
		return fsRestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTECC.FS_RESTYPE
	 * @param fsRestype  the value for TROUTECC.FS_RESTYPE
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public void setFsRestype(String fsRestype) {
		this.fsRestype = fsRestype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTECC.FS_ROUTENO
	 * @return  the value of TROUTECC.FS_ROUTENO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public String getFsRouteno() {
		return fsRouteno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTECC.FS_ROUTENO
	 * @param fsRouteno  the value for TROUTECC.FS_ROUTENO
	 * @mbggenerated  Tue Jan 19 23:27:48 CST 2016
	 */
	public void setFsRouteno(String fsRouteno) {
		this.fsRouteno = fsRouteno;
	}
}