package com.yttx.yttxps.model;

import java.math.BigDecimal;
import java.util.Date;

public class TRouteArrange {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FS_ID
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private String fsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FI_GENINDEX
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private BigDecimal fiGenindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FS_NAME
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private String fsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FS_REGIONS
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private String fsRegions;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FI_DAYS
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private BigDecimal fiDays;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FS_PROPERTY
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private String fsProperty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FT_STARTDATE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private Date ftStartdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FT_ENDDATE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private Date ftEnddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FS_STARTPLACE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private String fsStartplace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FS_TITLE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private String fsTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FS_TITLEPIC
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private String fsTitlepic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FS_SUMMARY
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private String fsSummary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TROUTEARRANGE.FI_STAT
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	private BigDecimal fiStat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FS_ID
	 * @return  the value of TROUTEARRANGE.FS_ID
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public String getFsId() {
		return fsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FS_ID
	 * @param fsId  the value for TROUTEARRANGE.FS_ID
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFsId(String fsId) {
		this.fsId = fsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FI_GENINDEX
	 * @return  the value of TROUTEARRANGE.FI_GENINDEX
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public BigDecimal getFiGenindex() {
		return fiGenindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FI_GENINDEX
	 * @param fiGenindex  the value for TROUTEARRANGE.FI_GENINDEX
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFiGenindex(BigDecimal fiGenindex) {
		this.fiGenindex = fiGenindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FS_NAME
	 * @return  the value of TROUTEARRANGE.FS_NAME
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public String getFsName() {
		return fsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FS_NAME
	 * @param fsName  the value for TROUTEARRANGE.FS_NAME
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFsName(String fsName) {
		this.fsName = fsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FS_REGIONS
	 * @return  the value of TROUTEARRANGE.FS_REGIONS
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public String getFsRegions() {
		return fsRegions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FS_REGIONS
	 * @param fsRegions  the value for TROUTEARRANGE.FS_REGIONS
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFsRegions(String fsRegions) {
		this.fsRegions = fsRegions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FI_DAYS
	 * @return  the value of TROUTEARRANGE.FI_DAYS
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public BigDecimal getFiDays() {
		return fiDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FI_DAYS
	 * @param fiDays  the value for TROUTEARRANGE.FI_DAYS
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFiDays(BigDecimal fiDays) {
		this.fiDays = fiDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FS_PROPERTY
	 * @return  the value of TROUTEARRANGE.FS_PROPERTY
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public String getFsProperty() {
		return fsProperty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FS_PROPERTY
	 * @param fsProperty  the value for TROUTEARRANGE.FS_PROPERTY
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFsProperty(String fsProperty) {
		this.fsProperty = fsProperty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FT_STARTDATE
	 * @return  the value of TROUTEARRANGE.FT_STARTDATE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public Date getFtStartdate() {
		return ftStartdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FT_STARTDATE
	 * @param ftStartdate  the value for TROUTEARRANGE.FT_STARTDATE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFtStartdate(Date ftStartdate) {
		this.ftStartdate = ftStartdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FT_ENDDATE
	 * @return  the value of TROUTEARRANGE.FT_ENDDATE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public Date getFtEnddate() {
		return ftEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FT_ENDDATE
	 * @param ftEnddate  the value for TROUTEARRANGE.FT_ENDDATE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFtEnddate(Date ftEnddate) {
		this.ftEnddate = ftEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FS_STARTPLACE
	 * @return  the value of TROUTEARRANGE.FS_STARTPLACE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public String getFsStartplace() {
		return fsStartplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FS_STARTPLACE
	 * @param fsStartplace  the value for TROUTEARRANGE.FS_STARTPLACE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFsStartplace(String fsStartplace) {
		this.fsStartplace = fsStartplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FS_TITLE
	 * @return  the value of TROUTEARRANGE.FS_TITLE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public String getFsTitle() {
		return fsTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FS_TITLE
	 * @param fsTitle  the value for TROUTEARRANGE.FS_TITLE
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFsTitle(String fsTitle) {
		this.fsTitle = fsTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FS_TITLEPIC
	 * @return  the value of TROUTEARRANGE.FS_TITLEPIC
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public String getFsTitlepic() {
		return fsTitlepic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FS_TITLEPIC
	 * @param fsTitlepic  the value for TROUTEARRANGE.FS_TITLEPIC
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFsTitlepic(String fsTitlepic) {
		this.fsTitlepic = fsTitlepic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FS_SUMMARY
	 * @return  the value of TROUTEARRANGE.FS_SUMMARY
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public String getFsSummary() {
		return fsSummary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FS_SUMMARY
	 * @param fsSummary  the value for TROUTEARRANGE.FS_SUMMARY
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFsSummary(String fsSummary) {
		this.fsSummary = fsSummary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TROUTEARRANGE.FI_STAT
	 * @return  the value of TROUTEARRANGE.FI_STAT
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public BigDecimal getFiStat() {
		return fiStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TROUTEARRANGE.FI_STAT
	 * @param fiStat  the value for TROUTEARRANGE.FI_STAT
	 * @mbggenerated  Thu Feb 04 10:26:31 CST 2016
	 */
	public void setFiStat(BigDecimal fiStat) {
		this.fiStat = fiStat;
	}
}