package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class TScenicGen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENICGEN.FI_INDEX
     *
     * @mbggenerated
     */
    private BigDecimal index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENICGEN.FS_SCENICNO
     *
     * @mbggenerated
     */
    private String scenicno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSCENICGEN.FI_GENINDEX
     *
     * @mbggenerated
     */
    private BigDecimal genindex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENICGEN.FI_INDEX
     *
     * @return the value of TSCENICGEN.FI_INDEX
     *
     * @mbggenerated
     */
    public BigDecimal getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENICGEN.FI_INDEX
     *
     * @param index the value for TSCENICGEN.FI_INDEX
     *
     * @mbggenerated
     */
    public void setIndex(BigDecimal index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENICGEN.FS_SCENICNO
     *
     * @return the value of TSCENICGEN.FS_SCENICNO
     *
     * @mbggenerated
     */
    public String getScenicno() {
        return scenicno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENICGEN.FS_SCENICNO
     *
     * @param scenicno the value for TSCENICGEN.FS_SCENICNO
     *
     * @mbggenerated
     */
    public void setScenicno(String scenicno) {
        this.scenicno = scenicno == null ? null : scenicno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSCENICGEN.FI_GENINDEX
     *
     * @return the value of TSCENICGEN.FI_GENINDEX
     *
     * @mbggenerated
     */
    public BigDecimal getGenindex() {
        return genindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSCENICGEN.FI_GENINDEX
     *
     * @param genindex the value for TSCENICGEN.FI_GENINDEX
     *
     * @mbggenerated
     */
    public void setGenindex(BigDecimal genindex) {
        this.genindex = genindex;
    }
}