package com.yttx.yttxps.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TticketExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public TticketExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFsNoIsNull() {
            addCriterion("fs_No is null");
            return (Criteria) this;
        }

        public Criteria andFsNoIsNotNull() {
            addCriterion("fs_No is not null");
            return (Criteria) this;
        }

        public Criteria andFsNoEqualTo(String value) {
            addCriterion("fs_No =", value, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoNotEqualTo(String value) {
            addCriterion("fs_No <>", value, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoGreaterThan(String value) {
            addCriterion("fs_No >", value, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoGreaterThanOrEqualTo(String value) {
            addCriterion("fs_No >=", value, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoLessThan(String value) {
            addCriterion("fs_No <", value, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoLessThanOrEqualTo(String value) {
            addCriterion("fs_No <=", value, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoLike(String value) {
            addCriterion("fs_No like", value, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoNotLike(String value) {
            addCriterion("fs_No not like", value, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoIn(List<String> values) {
            addCriterion("fs_No in", values, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoNotIn(List<String> values) {
            addCriterion("fs_No not in", values, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoBetween(String value1, String value2) {
            addCriterion("fs_No between", value1, value2, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNoNotBetween(String value1, String value2) {
            addCriterion("fs_No not between", value1, value2, "fsNo");
            return (Criteria) this;
        }

        public Criteria andFsNameIsNull() {
            addCriterion("fs_Name is null");
            return (Criteria) this;
        }

        public Criteria andFsNameIsNotNull() {
            addCriterion("fs_Name is not null");
            return (Criteria) this;
        }

        public Criteria andFsNameEqualTo(String value) {
            addCriterion("fs_Name =", value, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameNotEqualTo(String value) {
            addCriterion("fs_Name <>", value, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameGreaterThan(String value) {
            addCriterion("fs_Name >", value, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameGreaterThanOrEqualTo(String value) {
            addCriterion("fs_Name >=", value, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameLessThan(String value) {
            addCriterion("fs_Name <", value, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameLessThanOrEqualTo(String value) {
            addCriterion("fs_Name <=", value, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameLike(String value) {
            addCriterion("fs_Name like", value, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameNotLike(String value) {
            addCriterion("fs_Name not like", value, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameIn(List<String> values) {
            addCriterion("fs_Name in", values, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameNotIn(List<String> values) {
            addCriterion("fs_Name not in", values, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameBetween(String value1, String value2) {
            addCriterion("fs_Name between", value1, value2, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsNameNotBetween(String value1, String value2) {
            addCriterion("fs_Name not between", value1, value2, "fsName");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoIsNull() {
            addCriterion("fs_ScenicNo is null");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoIsNotNull() {
            addCriterion("fs_ScenicNo is not null");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoEqualTo(String value) {
            addCriterion("fs_ScenicNo =", value, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoNotEqualTo(String value) {
            addCriterion("fs_ScenicNo <>", value, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoGreaterThan(String value) {
            addCriterion("fs_ScenicNo >", value, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoGreaterThanOrEqualTo(String value) {
            addCriterion("fs_ScenicNo >=", value, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoLessThan(String value) {
            addCriterion("fs_ScenicNo <", value, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoLessThanOrEqualTo(String value) {
            addCriterion("fs_ScenicNo <=", value, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoLike(String value) {
            addCriterion("fs_ScenicNo like", value, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoNotLike(String value) {
            addCriterion("fs_ScenicNo not like", value, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoIn(List<String> values) {
            addCriterion("fs_ScenicNo in", values, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoNotIn(List<String> values) {
            addCriterion("fs_ScenicNo not in", values, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoBetween(String value1, String value2) {
            addCriterion("fs_ScenicNo between", value1, value2, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsScenicnoNotBetween(String value1, String value2) {
            addCriterion("fs_ScenicNo not between", value1, value2, "fsScenicno");
            return (Criteria) this;
        }

        public Criteria andFsTypeIsNull() {
            addCriterion("fs_Type is null");
            return (Criteria) this;
        }

        public Criteria andFsTypeIsNotNull() {
            addCriterion("fs_Type is not null");
            return (Criteria) this;
        }

        public Criteria andFsTypeEqualTo(String value) {
            addCriterion("fs_Type =", value, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeNotEqualTo(String value) {
            addCriterion("fs_Type <>", value, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeGreaterThan(String value) {
            addCriterion("fs_Type >", value, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("fs_Type >=", value, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeLessThan(String value) {
            addCriterion("fs_Type <", value, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeLessThanOrEqualTo(String value) {
            addCriterion("fs_Type <=", value, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeLike(String value) {
            addCriterion("fs_Type like", value, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeNotLike(String value) {
            addCriterion("fs_Type not like", value, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeIn(List<String> values) {
            addCriterion("fs_Type in", values, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeNotIn(List<String> values) {
            addCriterion("fs_Type not in", values, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeBetween(String value1, String value2) {
            addCriterion("fs_Type between", value1, value2, "fsType");
            return (Criteria) this;
        }

        public Criteria andFsTypeNotBetween(String value1, String value2) {
            addCriterion("fs_Type not between", value1, value2, "fsType");
            return (Criteria) this;
        }

        public Criteria andFiSeqIsNull() {
            addCriterion("fi_Seq is null");
            return (Criteria) this;
        }

        public Criteria andFiSeqIsNotNull() {
            addCriterion("fi_Seq is not null");
            return (Criteria) this;
        }

        public Criteria andFiSeqEqualTo(Integer value) {
            addCriterion("fi_Seq =", value, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFiSeqNotEqualTo(Integer value) {
            addCriterion("fi_Seq <>", value, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFiSeqGreaterThan(Integer value) {
            addCriterion("fi_Seq >", value, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFiSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("fi_Seq >=", value, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFiSeqLessThan(Integer value) {
            addCriterion("fi_Seq <", value, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFiSeqLessThanOrEqualTo(Integer value) {
            addCriterion("fi_Seq <=", value, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFiSeqIn(List<Integer> values) {
            addCriterion("fi_Seq in", values, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFiSeqNotIn(List<Integer> values) {
            addCriterion("fi_Seq not in", values, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFiSeqBetween(Integer value1, Integer value2) {
            addCriterion("fi_Seq between", value1, value2, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFiSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("fi_Seq not between", value1, value2, "fiSeq");
            return (Criteria) this;
        }

        public Criteria andFsDescIsNull() {
            addCriterion("fs_Desc is null");
            return (Criteria) this;
        }

        public Criteria andFsDescIsNotNull() {
            addCriterion("fs_Desc is not null");
            return (Criteria) this;
        }

        public Criteria andFsDescEqualTo(String value) {
            addCriterion("fs_Desc =", value, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescNotEqualTo(String value) {
            addCriterion("fs_Desc <>", value, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescGreaterThan(String value) {
            addCriterion("fs_Desc >", value, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescGreaterThanOrEqualTo(String value) {
            addCriterion("fs_Desc >=", value, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescLessThan(String value) {
            addCriterion("fs_Desc <", value, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescLessThanOrEqualTo(String value) {
            addCriterion("fs_Desc <=", value, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescLike(String value) {
            addCriterion("fs_Desc like", value, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescNotLike(String value) {
            addCriterion("fs_Desc not like", value, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescIn(List<String> values) {
            addCriterion("fs_Desc in", values, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescNotIn(List<String> values) {
            addCriterion("fs_Desc not in", values, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescBetween(String value1, String value2) {
            addCriterion("fs_Desc between", value1, value2, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFsDescNotBetween(String value1, String value2) {
            addCriterion("fs_Desc not between", value1, value2, "fsDesc");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpIsNull() {
            addCriterion("fd_Full_Low_QP is null");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpIsNotNull() {
            addCriterion("fd_Full_Low_QP is not null");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Low_QP =", value, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Low_QP <>", value, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpGreaterThan(BigDecimal value) {
            addCriterion("fd_Full_Low_QP >", value, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Low_QP >=", value, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpLessThan(BigDecimal value) {
            addCriterion("fd_Full_Low_QP <", value, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Low_QP <=", value, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpIn(List<BigDecimal> values) {
            addCriterion("fd_Full_Low_QP in", values, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Full_Low_QP not in", values, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Full_Low_QP between", value1, value2, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowQpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Full_Low_QP not between", value1, value2, "fdFullLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpIsNull() {
            addCriterion("fd_Half_Low_QP is null");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpIsNotNull() {
            addCriterion("fd_Half_Low_QP is not null");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Low_QP =", value, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Low_QP <>", value, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpGreaterThan(BigDecimal value) {
            addCriterion("fd_Half_Low_QP >", value, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Low_QP >=", value, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpLessThan(BigDecimal value) {
            addCriterion("fd_Half_Low_QP <", value, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Low_QP <=", value, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpIn(List<BigDecimal> values) {
            addCriterion("fd_Half_Low_QP in", values, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Half_Low_QP not in", values, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Half_Low_QP between", value1, value2, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowQpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Half_Low_QP not between", value1, value2, "fdHalfLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpIsNull() {
            addCriterion("fd_Child_Low_QP is null");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpIsNotNull() {
            addCriterion("fd_Child_Low_QP is not null");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Low_QP =", value, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Low_QP <>", value, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpGreaterThan(BigDecimal value) {
            addCriterion("fd_Child_Low_QP >", value, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Low_QP >=", value, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpLessThan(BigDecimal value) {
            addCriterion("fd_Child_Low_QP <", value, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Low_QP <=", value, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpIn(List<BigDecimal> values) {
            addCriterion("fd_Child_Low_QP in", values, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Child_Low_QP not in", values, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Child_Low_QP between", value1, value2, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowQpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Child_Low_QP not between", value1, value2, "fdChildLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpIsNull() {
            addCriterion("fd_Free_Low_QP is null");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpIsNotNull() {
            addCriterion("fd_Free_Low_QP is not null");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Low_QP =", value, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Low_QP <>", value, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpGreaterThan(BigDecimal value) {
            addCriterion("fd_Free_Low_QP >", value, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Low_QP >=", value, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpLessThan(BigDecimal value) {
            addCriterion("fd_Free_Low_QP <", value, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Low_QP <=", value, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpIn(List<BigDecimal> values) {
            addCriterion("fd_Free_Low_QP in", values, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Free_Low_QP not in", values, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Free_Low_QP between", value1, value2, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowQpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Free_Low_QP not between", value1, value2, "fdFreeLowQp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpIsNull() {
            addCriterion("fd_Full_Low_TP is null");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpIsNotNull() {
            addCriterion("fd_Full_Low_TP is not null");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Low_TP =", value, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Low_TP <>", value, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpGreaterThan(BigDecimal value) {
            addCriterion("fd_Full_Low_TP >", value, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Low_TP >=", value, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpLessThan(BigDecimal value) {
            addCriterion("fd_Full_Low_TP <", value, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Low_TP <=", value, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpIn(List<BigDecimal> values) {
            addCriterion("fd_Full_Low_TP in", values, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Full_Low_TP not in", values, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Full_Low_TP between", value1, value2, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullLowTpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Full_Low_TP not between", value1, value2, "fdFullLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpIsNull() {
            addCriterion("fd_Half_Low_TP is null");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpIsNotNull() {
            addCriterion("fd_Half_Low_TP is not null");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Low_TP =", value, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Low_TP <>", value, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpGreaterThan(BigDecimal value) {
            addCriterion("fd_Half_Low_TP >", value, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Low_TP >=", value, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpLessThan(BigDecimal value) {
            addCriterion("fd_Half_Low_TP <", value, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Low_TP <=", value, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpIn(List<BigDecimal> values) {
            addCriterion("fd_Half_Low_TP in", values, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Half_Low_TP not in", values, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Half_Low_TP between", value1, value2, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfLowTpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Half_Low_TP not between", value1, value2, "fdHalfLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpIsNull() {
            addCriterion("fd_Child_Low_TP is null");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpIsNotNull() {
            addCriterion("fd_Child_Low_TP is not null");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Low_TP =", value, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Low_TP <>", value, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpGreaterThan(BigDecimal value) {
            addCriterion("fd_Child_Low_TP >", value, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Low_TP >=", value, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpLessThan(BigDecimal value) {
            addCriterion("fd_Child_Low_TP <", value, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Low_TP <=", value, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpIn(List<BigDecimal> values) {
            addCriterion("fd_Child_Low_TP in", values, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Child_Low_TP not in", values, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Child_Low_TP between", value1, value2, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdChildLowTpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Child_Low_TP not between", value1, value2, "fdChildLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpIsNull() {
            addCriterion("fd_Free_Low_TP is null");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpIsNotNull() {
            addCriterion("fd_Free_Low_TP is not null");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Low_TP =", value, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Low_TP <>", value, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpGreaterThan(BigDecimal value) {
            addCriterion("fd_Free_Low_TP >", value, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Low_TP >=", value, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpLessThan(BigDecimal value) {
            addCriterion("fd_Free_Low_TP <", value, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Low_TP <=", value, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpIn(List<BigDecimal> values) {
            addCriterion("fd_Free_Low_TP in", values, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Free_Low_TP not in", values, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Free_Low_TP between", value1, value2, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFreeLowTpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Free_Low_TP not between", value1, value2, "fdFreeLowTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpIsNull() {
            addCriterion("fd_Full_Peak_QP is null");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpIsNotNull() {
            addCriterion("fd_Full_Peak_QP is not null");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Peak_QP =", value, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Peak_QP <>", value, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpGreaterThan(BigDecimal value) {
            addCriterion("fd_Full_Peak_QP >", value, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Peak_QP >=", value, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpLessThan(BigDecimal value) {
            addCriterion("fd_Full_Peak_QP <", value, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Peak_QP <=", value, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpIn(List<BigDecimal> values) {
            addCriterion("fd_Full_Peak_QP in", values, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Full_Peak_QP not in", values, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Full_Peak_QP between", value1, value2, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakQpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Full_Peak_QP not between", value1, value2, "fdFullPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpIsNull() {
            addCriterion("fd_Half_Peak_QP is null");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpIsNotNull() {
            addCriterion("fd_Half_Peak_QP is not null");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Peak_QP =", value, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Peak_QP <>", value, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpGreaterThan(BigDecimal value) {
            addCriterion("fd_Half_Peak_QP >", value, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Peak_QP >=", value, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpLessThan(BigDecimal value) {
            addCriterion("fd_Half_Peak_QP <", value, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Peak_QP <=", value, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpIn(List<BigDecimal> values) {
            addCriterion("fd_Half_Peak_QP in", values, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Half_Peak_QP not in", values, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Half_Peak_QP between", value1, value2, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakQpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Half_Peak_QP not between", value1, value2, "fdHalfPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpIsNull() {
            addCriterion("fd_Child_Peak_QP is null");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpIsNotNull() {
            addCriterion("fd_Child_Peak_QP is not null");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Peak_QP =", value, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Peak_QP <>", value, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpGreaterThan(BigDecimal value) {
            addCriterion("fd_Child_Peak_QP >", value, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Peak_QP >=", value, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpLessThan(BigDecimal value) {
            addCriterion("fd_Child_Peak_QP <", value, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Peak_QP <=", value, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpIn(List<BigDecimal> values) {
            addCriterion("fd_Child_Peak_QP in", values, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Child_Peak_QP not in", values, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Child_Peak_QP between", value1, value2, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakQpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Child_Peak_QP not between", value1, value2, "fdChildPeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpIsNull() {
            addCriterion("fd_Free_Peak_QP is null");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpIsNotNull() {
            addCriterion("fd_Free_Peak_QP is not null");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Peak_QP =", value, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Peak_QP <>", value, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpGreaterThan(BigDecimal value) {
            addCriterion("fd_Free_Peak_QP >", value, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Peak_QP >=", value, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpLessThan(BigDecimal value) {
            addCriterion("fd_Free_Peak_QP <", value, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Peak_QP <=", value, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpIn(List<BigDecimal> values) {
            addCriterion("fd_Free_Peak_QP in", values, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Free_Peak_QP not in", values, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Free_Peak_QP between", value1, value2, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakQpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Free_Peak_QP not between", value1, value2, "fdFreePeakQp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpIsNull() {
            addCriterion("fd_Full_Peak_TP is null");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpIsNotNull() {
            addCriterion("fd_Full_Peak_TP is not null");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Peak_TP =", value, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Peak_TP <>", value, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpGreaterThan(BigDecimal value) {
            addCriterion("fd_Full_Peak_TP >", value, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Peak_TP >=", value, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpLessThan(BigDecimal value) {
            addCriterion("fd_Full_Peak_TP <", value, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Full_Peak_TP <=", value, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpIn(List<BigDecimal> values) {
            addCriterion("fd_Full_Peak_TP in", values, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Full_Peak_TP not in", values, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Full_Peak_TP between", value1, value2, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFullPeakTpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Full_Peak_TP not between", value1, value2, "fdFullPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpIsNull() {
            addCriterion("fd_Half_Peak_TP is null");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpIsNotNull() {
            addCriterion("fd_Half_Peak_TP is not null");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Peak_TP =", value, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Peak_TP <>", value, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpGreaterThan(BigDecimal value) {
            addCriterion("fd_Half_Peak_TP >", value, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Peak_TP >=", value, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpLessThan(BigDecimal value) {
            addCriterion("fd_Half_Peak_TP <", value, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Half_Peak_TP <=", value, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpIn(List<BigDecimal> values) {
            addCriterion("fd_Half_Peak_TP in", values, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Half_Peak_TP not in", values, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Half_Peak_TP between", value1, value2, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdHalfPeakTpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Half_Peak_TP not between", value1, value2, "fdHalfPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpIsNull() {
            addCriterion("fd_Child_Peak_TP is null");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpIsNotNull() {
            addCriterion("fd_Child_Peak_TP is not null");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Peak_TP =", value, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Peak_TP <>", value, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpGreaterThan(BigDecimal value) {
            addCriterion("fd_Child_Peak_TP >", value, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Peak_TP >=", value, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpLessThan(BigDecimal value) {
            addCriterion("fd_Child_Peak_TP <", value, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Child_Peak_TP <=", value, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpIn(List<BigDecimal> values) {
            addCriterion("fd_Child_Peak_TP in", values, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Child_Peak_TP not in", values, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Child_Peak_TP between", value1, value2, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdChildPeakTpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Child_Peak_TP not between", value1, value2, "fdChildPeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpIsNull() {
            addCriterion("fd_Free_Peak_TP is null");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpIsNotNull() {
            addCriterion("fd_Free_Peak_TP is not null");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Peak_TP =", value, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpNotEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Peak_TP <>", value, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpGreaterThan(BigDecimal value) {
            addCriterion("fd_Free_Peak_TP >", value, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Peak_TP >=", value, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpLessThan(BigDecimal value) {
            addCriterion("fd_Free_Peak_TP <", value, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fd_Free_Peak_TP <=", value, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpIn(List<BigDecimal> values) {
            addCriterion("fd_Free_Peak_TP in", values, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpNotIn(List<BigDecimal> values) {
            addCriterion("fd_Free_Peak_TP not in", values, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Free_Peak_TP between", value1, value2, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFdFreePeakTpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fd_Free_Peak_TP not between", value1, value2, "fdFreePeakTp");
            return (Criteria) this;
        }

        public Criteria andFiStatIsNull() {
            addCriterion("fi_Stat is null");
            return (Criteria) this;
        }

        public Criteria andFiStatIsNotNull() {
            addCriterion("fi_Stat is not null");
            return (Criteria) this;
        }

        public Criteria andFiStatEqualTo(Integer value) {
            addCriterion("fi_Stat =", value, "fiStat");
            return (Criteria) this;
        }

        public Criteria andFiStatNotEqualTo(Integer value) {
            addCriterion("fi_Stat <>", value, "fiStat");
            return (Criteria) this;
        }

        public Criteria andFiStatGreaterThan(Integer value) {
            addCriterion("fi_Stat >", value, "fiStat");
            return (Criteria) this;
        }

        public Criteria andFiStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("fi_Stat >=", value, "fiStat");
            return (Criteria) this;
        }

        public Criteria andFiStatLessThan(Integer value) {
            addCriterion("fi_Stat <", value, "fiStat");
            return (Criteria) this;
        }

        public Criteria andFiStatLessThanOrEqualTo(Integer value) {
            addCriterion("fi_Stat <=", value, "fiStat");
            return (Criteria) this;
        }

        public Criteria andFiStatIn(List<Integer> values) {
            addCriterion("fi_Stat in", values, "fiStat");
            return (Criteria) this;
        }

        public Criteria andFiStatNotIn(List<Integer> values) {
            addCriterion("fi_Stat not in", values, "fiStat");
            return (Criteria) this;
        }

        public Criteria andFiStatBetween(Integer value1, Integer value2) {
            addCriterion("fi_Stat between", value1, value2, "fiStat");
            return (Criteria) this;
        }

        public Criteria andFiStatNotBetween(Integer value1, Integer value2) {
            addCriterion("fi_Stat not between", value1, value2, "fiStat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tticket
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 07 16:39:49 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tticket
     *
     * @mbggenerated Thu Jan 07 16:39:49 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}