package com.yttx.yttxps.model;

import java.math.BigDecimal;

public class TtransportArrangeKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRANSPORTARRANGE.FI_GENINDEX
	 * @mbggenerated  Sun Jan 31 15:49:49 CST 2016
	 */
	private BigDecimal fiGenindex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRANSPORTARRANGE.FS_NO
	 * @mbggenerated  Sun Jan 31 15:49:49 CST 2016
	 */
	private String fsNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TTRANSPORTARRANGE.FS_TRANSNO
	 * @mbggenerated  Sun Jan 31 15:49:49 CST 2016
	 */
	private String fsTransno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRANSPORTARRANGE.FI_GENINDEX
	 * @return  the value of TTRANSPORTARRANGE.FI_GENINDEX
	 * @mbggenerated  Sun Jan 31 15:49:49 CST 2016
	 */
	public BigDecimal getFiGenindex() {
		return fiGenindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRANSPORTARRANGE.FI_GENINDEX
	 * @param fiGenindex  the value for TTRANSPORTARRANGE.FI_GENINDEX
	 * @mbggenerated  Sun Jan 31 15:49:49 CST 2016
	 */
	public void setFiGenindex(BigDecimal fiGenindex) {
		this.fiGenindex = fiGenindex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRANSPORTARRANGE.FS_NO
	 * @return  the value of TTRANSPORTARRANGE.FS_NO
	 * @mbggenerated  Sun Jan 31 15:49:49 CST 2016
	 */
	public String getFsNo() {
		return fsNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRANSPORTARRANGE.FS_NO
	 * @param fsNo  the value for TTRANSPORTARRANGE.FS_NO
	 * @mbggenerated  Sun Jan 31 15:49:49 CST 2016
	 */
	public void setFsNo(String fsNo) {
		this.fsNo = fsNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TTRANSPORTARRANGE.FS_TRANSNO
	 * @return  the value of TTRANSPORTARRANGE.FS_TRANSNO
	 * @mbggenerated  Sun Jan 31 15:49:49 CST 2016
	 */
	public String getFsTransno() {
		return fsTransno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TTRANSPORTARRANGE.FS_TRANSNO
	 * @param fsTransno  the value for TTRANSPORTARRANGE.FS_TRANSNO
	 * @mbggenerated  Sun Jan 31 15:49:49 CST 2016
	 */
	public void setFsTransno(String fsTransno) {
		this.fsTransno = fsTransno;
	}
}